"use client";

import { useEffect, useState } from "react";
import { Footer, RevealObserver, SiteHeader } from "./site-shell";

const whatsappUrl = "https://wa.me/447879812789";

const reportTiers = [
  { number: "01", name: "Smaller charities", income: "Up to £500k", price: "From £1,000", copy: "For smaller charities where proportionate impact reporting is appropriate.", sorp: "Report your main achievements and consider how the charity’s work made a difference to beneficiaries and wider society." },
  { number: "02", name: "Medium-sized charities", income: "Over £500k to £15m", price: "From £2,500", copy: "For charities with more detailed expectations and greater programme, organisational and evidence complexity.", sorp: "Explain performance against aims and objectives and the impact the charity is making, using measures, activities, outputs and outcomes." },
  { number: "03", name: "Largest charities", income: "Over £15m", price: "Bespoke pricing", copy: "For the largest and most complex charities, where measurement, analysis, engagement and reporting require a broader scope.", sorp: "Meet Tier 1 and Tier 2 requirements together with the additional reporting requirements applying to the largest charities." },
] as const;

const supportPlans = [
  ["Light-touch support", "From £250 / month", "Regular impact check-ins and guidance for smaller organisations."],
  ["Ongoing impact partner", "From £500 / month", "More regular support with measurement, evidence, reporting and management information."],
  ["Outsourced Impact Director", "From £1,000 / month", "Senior impact expertise embedded alongside your leadership team, without the full-time hire."],
] as const;

const sections = [
  ["impact-reports", "Impact reports"], ["sorp-2026", "SORP 2026"], ["excellence", "Social Impact Excellence"], ["data", "Data"], ["year-round", "Year-round support"], ["accountants", "For accountants"], ["why-us", "Why us"],
] as const;

function MajorLabel({ children }: { children: React.ReactNode }) { return <p className="cir-major-label">{children}</p>; }

function ContactActions({ inverse = false }: { inverse?: boolean }) {
  return <div className={`cir-contact-actions ${inverse ? "is-inverse" : ""}`}><a className="cir-primary-action" href="mailto:marcus@mysocialimpact.org">Talk to us about your impact report <span>→</span></a><div><a href="mailto:marcus@mysocialimpact.org">Marcus@mysocialimpact.org</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp +44 7879 812789 ↗</a></div></div>;
}

function ReportNavigation() {
  const [active, setActive] = useState("impact-reports");
  useEffect(() => {
    const update = () => {
      const readingLine = window.innerHeight * .38;
      const reached = sections.filter(([id]) => {
        const element = document.getElementById(id);
        return element ? element.getBoundingClientRect().top <= readingLine : false;
      });
      setActive(reached.length ? reached[reached.length - 1][0] : "impact-reports");
    };
    update(); window.addEventListener("scroll", update, { passive: true });
    return () => window.removeEventListener("scroll", update);
  }, []);
  useEffect(() => { document.querySelector<HTMLAnchorElement>(`.cir-subnav a[href="#${active}"]`)?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" }); }, [active]);
  return <nav className="cir-subnav" aria-label="Charity Impact Reports sections"><div>{sections.map(([id, label]) => <a key={id} className={active === id ? "is-active" : ""} href={`#${id}`} aria-current={active === id ? "location" : undefined}>{label}</a>)}</div></nav>;
}

function ImpactJourney({ compact = false }: { compact?: boolean }) {
  const items = compact ? [["Measure", "Define what matters"], ["Review", "Read the evidence"], ["Learn", "Understand what works"], ["Improve", "Make better decisions"], ["Report", "Show the difference"]] : [["Activities", "What did you do?"], ["Outputs", "Who did you reach?"], ["Outcomes", "What changed?"], ["Impact", "What difference did it make?"]];
  return <div className={`cir-journey ${compact ? "is-five" : ""}`}>{items.map(([title, copy], index) => <div key={title}><span>0{index + 1}</span><strong>{title}</strong><p>{copy}</p></div>)}</div>;
}

export function CharityImpactReportsPage() {
  return <><RevealObserver /><SiteHeader /><ReportNavigation /><main className="cir-page">
    <section className="cir-hero" id="impact-reports"><div className="cir-hero-kicker" data-reveal><span>Charity Impact Reports</span><b>From £1,000</b></div><h1 data-reveal>Imagine if better evidence helped more money reach organisations making a meaningful difference.</h1><div className="cir-hero-foot" data-reveal><p>There is already extraordinary commitment, energy and funding going into solving social and environmental problems. Better evidence helps all of us understand what works, and make better decisions about what happens next.</p><a href="#opening">Explore the idea <span>↓</span></a></div><i className="cir-paint cir-paint-pink" aria-hidden="true" /></section>

    <section className="cir-opening" id="opening"><MajorLabel>The challenges are big</MajorLabel><div className="cir-challenges" data-reveal>{["Climate change", "Poverty", "Health inequality", "Education", "Isolation", "Conflict", "Biodiversity loss", "Opportunity"].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div><div className="cir-opening-copy" data-reveal><h2>No organisation solves challenges like these alone.</h2><div><p>Progress happens when charities, communities, donors, funders, businesses, governments and individuals bring their different strengths together.</p><p>If we are serious about solving difficult social and environmental problems, we need to become better at understanding what works.</p><strong>Better evidence does not replace passion.<br />It helps passion travel further.</strong></div></div></section>

    <section className="cir-report-idea"><div data-reveal><p className="cir-eyebrow">That is where impact reporting becomes interesting.</p><h2>A good Impact Report is not simply a document describing what an organisation did.</h2></div><div className="cir-questions" data-reveal>{["What changed?", "For whom?", "How do we know?", "What did we learn?", "What should we do next?"].map((question, index) => <span key={question}><b>0{index + 1}</b>{question}</span>)}</div></section>

    <section className="cir-proposition"><MajorLabel>Show the difference you make</MajorLabel><div className="cir-proposition-grid" data-reveal><h2>Charity Impact Reports that go beyond what you did to show what changed.</h2><div><p className="cir-lead">Charities exist to make a difference. Demonstrating that difference clearly, credibly and with evidence isn’t always easy.</p><p>My Social Impact helps charities measure, understand and communicate their impact.</p><p>We create Charity Impact Reports, help organisations establish the right measures and data, and provide ongoing support so impact becomes part of how the charity is managed throughout the year.</p><p>With Charities SORP 2026, achievements, outcomes and impact have become an increasingly important part of charity reporting.</p></div></div><ImpactJourney /><div className="cir-price-callout" data-reveal><span>Charity Impact Reports</span><strong>From £1,000</strong><ContactActions inverse /></div></section>

    <section className="cir-commercial"><div className="cir-section-intro" data-reveal><MajorLabel>Choose the right starting point</MajorLabel><h2>One clear framework.<br />Two ways to work with us.</h2><p>A Charity Impact Report can be a one-off project. For many charities, the more valuable approach is ongoing support that makes impact part of management throughout the year.</p></div><div className="cir-commercial-split"><div className="cir-tier-panel" data-reveal><p className="cir-eyebrow">One-off Charity Impact Reports</p><div className="cir-tier-grid">{reportTiers.map((tier) => <article key={tier.name}><span>{tier.number}</span><p>{tier.name}</p><h3>{tier.income}</h3><strong>{tier.price}</strong><p>{tier.copy}</p><small>{tier.sorp}</small></article>)}</div><p className="cir-caveat">These categories follow the SORP 2026 reporting tiers as a useful starting framework; SORP does not determine our fees. Final scope depends on programme complexity, existing evidence, analysis, research, writing and design. The tiers apply to charities preparing accruals accounts under the SORP; some smaller non-company charities may be eligible to prepare receipts and payments accounts.</p></div><div className="cir-support-panel" data-reveal><p className="cir-eyebrow">Impact support throughout the year</p><h2>The best time to think about impact is not when the annual report is due.</h2><p>Monthly support includes regular check-ins, practical guidance and senior thinking, not simply spreading the cost of a report.</p><p className="cir-not-finance">This is not report finance.<br /><strong>This is ongoing impact support.</strong></p><div className="cir-plan-list">{supportPlans.map(([name, price, copy]) => <article key={name}><p>{name}</p><strong>{price}</strong><span>{copy}</span></article>)}</div></div></div>
    <div className="cir-director" data-reveal><div><p className="cir-eyebrow">Your outsourced Impact Director</p><h2>Senior impact expertise, without the full-time hire.</h2></div><div><p>For charities that need ongoing senior expertise but do not need, or cannot justify, a full-time internal Impact Director.</p><ul>{["Monthly or fortnightly check-ins", "Impact strategy and KPI development", "Data, dashboard and evidence review", "Management and trustee preparation", "Annual reporting and SORP readiness", "Ongoing advice as priorities change"].map((item) => <li key={item}>{item}</li>)}</ul><p>We work as an extension of your team, providing challenge and support without taking over executive or trustee responsibility.</p></div></div><div className="cir-management-message" data-reveal><h2>A great Impact Report is valuable.</h2><p>But the strongest impact reporting is usually the result of good impact management throughout the year.</p><ImpactJourney compact /><ContactActions /></div></section>

    <section className="cir-sorp" id="sorp-2026"><div className="cir-section-intro" data-reveal><MajorLabel>SORP 2026</MajorLabel><h2>Why does this matter now?</h2><p>Funders, donors, trustees, partners and beneficiaries increasingly want to understand not simply what a charity does, but what it achieves. SORP 2026 reinforces that direction.</p></div><div className="cir-sorp-tool" data-reveal><div><p className="cir-eyebrow">Free SORP 2026 tool</p><h3>SORP says. AI helps interpret. Humans decide.</h3><p>Ask practical questions, explore the source paragraphs and use the answers to support informed human judgement.</p></div><a className="cir-primary-action" href="https://sorp2026.mysocialimpact.org" target="_blank" rel="noreferrer">Ask SORP 2026 <span>→</span></a></div><div className="cir-date" data-reveal><span>Effective for accounting periods beginning on or after</span><strong>1 January<br />2026</strong></div><div className="cir-sorp-tiers" data-reveal>{reportTiers.map((tier) => <article key={tier.name}><span>{tier.number}</span><p>{tier.name}</p><h3>{tier.income}</h3><p>{tier.sorp}</p></article>)}</div><p className="cir-caveat">These SORP tiers apply to charities preparing accruals accounts. Some smaller non-company charities may instead be eligible to prepare receipts and payments accounts. If in doubt, speak to your accountant or independent examiner.</p></section>

    <section className="cir-excellence" id="excellence"><div className="cir-section-intro" data-reveal><MajorLabel>Social Impact Excellence</MajorLabel><h2>Impact works best as a management discipline, not an annual exercise.</h2><p>Our flagship framework brings five connected pillars together, helping organisations make impact part of everyday leadership and delivery.</p></div><div className="cir-pillars" data-reveal>{[["Purpose", "Define the change you exist to create."], ["Leadership", "Create ownership, direction and accountability."], ["Data", "Build useful evidence and measures."], ["Delivery", "Turn intent into consistent action."], ["Communication", "Explain impact clearly and credibly."]].map(([name, copy], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{copy}</p></article>)}</div><div className="cir-statement" data-reveal><span>Purpose</span><i>+</i><span>Leadership</span><i>+</i><span>Data</span><i>+</i><span>Delivery</span><i>+</i><span>Communication</span><b>= Social Impact Excellence</b></div><a className="cir-primary-action" href="https://platform.mysocialimpact.org/" target="_blank" rel="noreferrer" data-reveal>Start your 10–15 minute Social Impact Maturity Snapshot <span>↗</span></a></section>

    <section className="cir-data" id="data"><div className="cir-section-intro" data-reveal><MajorLabel>Data</MajorLabel><h2>Count what happened.<br />Understand what changed.</h2><p>Good impact data connects activity to real change. It creates a line of sight from what you did to the difference it made.</p></div><div className="cir-data-chain" data-reveal>{[["Activity", "200 training sessions"], ["Output", "1,400 people attended"], ["Outcome", "82% gained a new skill"], ["Impact", "What changed in their lives as a result?"]].map(([name, example], index) => <article key={name}><span>0{index + 1}</span><p>{name}</p><strong>{example}</strong></article>)}</div><div className="cir-dashboard" data-reveal><div className="cir-dashboard-head"><div><p>Illustrative impact dashboard</p><h3>Skills for opportunity</h3></div><span>Reporting period · 2026</span></div><div className="cir-dashboard-grid"><article><span>People reached</span><strong>1,400</strong><i>↑ 18% year on year</i></article><article><span>Completed programme</span><strong>91%</strong><i>Target 85%</i></article><article><span>Gained a new skill</span><strong>82%</strong><i>1,148 people</i></article><article className="cir-dashboard-wide"><span>Progress towards intended outcomes</span><div><b style={{ "--value": "82%" } as React.CSSProperties}>Skills gained <em>82%</em></b><b style={{ "--value": "68%" } as React.CSSProperties}>Confidence improved <em>68%</em></b><b style={{ "--value": "54%" } as React.CSSProperties}>New opportunity secured <em>54%</em></b></div></article><article className="cir-dashboard-question"><span>The question that matters next</span><strong>Did those new skills create lasting opportunity?</strong></article></div></div><div className="cir-equation" data-reveal><p>Doing good isn’t quite the same as demonstrating it.</p><div><span>Numbers</span><i>+</i><span>Evidence</span><i>+</i><span>People</span><i>+</i><span>Stories</span><b>= A better picture of impact</b></div></div></section>

    <section className="cir-year-round" id="year-round"><div className="cir-section-intro" data-reveal><MajorLabel>Year-round support</MajorLabel><h2>Don’t wait until year-end.</h2><p>The worst time to discover you don’t have the data is when you’re writing the report.</p></div><div className="cir-cycle" data-reveal>{["Set impact objectives", "Choose KPIs", "Collect evidence", "Review the data", "Learn & adapt", "Communicate"].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}<i>↺</i></div><blockquote data-reveal>At year-end, the Impact Report should be <strong>the result of the process.</strong><br />Not an archaeological dig through twelve months of spreadsheets.</blockquote><div className="cir-year-round-grid" data-reveal><div><h3>What we can support</h3><ul>{["Impact measures and KPIs", "Data collection and evidence gaps", "Dashboards and management information", "Beneficiary stories and research", "Trustee discussions and reporting readiness", "Learning, review and better decisions"].map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="cir-eyebrow">An Impact Director, without the full-time hire</p><h3>We become the senior impact capability your team can call on throughout the year.</h3><p>Regular check-ins keep the work moving, the evidence useful and the organisation ready to report with confidence.</p><strong>From £1,000 / month</strong></div></div><ContactActions /></section>

    <section className="cir-accountants" id="accountants"><div className="cir-section-intro" data-reveal><MajorLabel>For accountants</MajorLabel><h2>We work with you.<br />We don’t replace you.</h2><p>Accountants bring essential expertise in financial reporting, assurance and charity compliance. We add specialist social impact measurement, evidence and communication.</p></div><div className="cir-accountant-equation" data-reveal><div><span>Financial reporting</span><strong>Your accountant</strong></div><i>+</i><div><span>Impact reporting</span><strong>My Social Impact</strong></div><i>=</i><div className="result"><span>One joined-up view</span><strong>A more complete picture of performance</strong></div></div><div className="cir-accountant-copy" data-reveal><h3>Stronger reporting through complementary expertise.</h3><div><p>We can work alongside accountancy firms, independent examiners and charity finance teams to strengthen the achievements, outcomes and impact story within the Trustees’ Annual Report.</p><p>You retain the financial reporting and assurance relationship. We bring the social impact discipline.</p><a href="mailto:marcus@mysocialimpact.org?subject=Working%20with%20My%20Social%20Impact"><span><strong>Work with us</strong><small>marcus@mysocialimpact.org</small></span><b aria-hidden="true">→</b></a></div></div></section>

    <section className="cir-why" id="why-us"><div className="cir-section-intro" data-reveal><MajorLabel>Why us</MajorLabel><h2>Finance discipline.<br />Impact thinking.<br />Human communication.</h2><p>Our work brings together years of social impact consulting, charity and purpose-led organisations, accounting, measurement, data and communication.</p></div><div className="cir-accounting-question" data-reveal><h2>What if some of the discipline of accounting could be applied to social impact?</h2><div><p>Not because everything valuable can be reduced to pounds and pence.</p><p>Because social impact deserves rigour around:</p><div>{["Evidence", "Measurement", "Consistency", "Accountability", "Reporting"].map((item) => <span key={item}>{item}</span>)}</div></div></div><div className="cir-finally" data-reveal><p>When SORP 2026 places greater emphasis on achievements, outcomes and impact, our reaction isn’t:</p><blockquote>“Quick. We’d better get into impact reporting.”</blockquote><p>It’s closer to:</p><strong>Finally.</strong></div><div className="cir-final-position" data-reveal><p>We are rather grateful to SORP 2026. Not because charities needed another piece of regulation. Because impact matters.</p><div><p>Charities should be able to demonstrate the difference they make.</p><p>Trustees should have information that helps them make better decisions.</p><p>Funders and donors should be able to understand what their support achieved.</p><p>Beneficiaries deserve organisations that learn what works, and what doesn’t.</p></div><h2>The better we become at understanding what works, the better we can direct our time, energy and resources towards approaches creating meaningful change.</h2><p>None of us solves the world’s biggest social and environmental challenges alone. But better evidence can help all of us contribute more effectively.</p></div><div className="cir-final-cta" data-reveal><MajorLabel>What do you need?</MajorLabel><div>{[["I need an Impact Report.", "From £1,000", "Let’s talk", "mailto:marcus@mysocialimpact.org?subject=Charity%20Impact%20Report"], ["We need to get ready for SORP 2026.", "Practical support", "Get SORP-ready", "mailto:marcus@mysocialimpact.org?subject=SORP%202026%20readiness"], ["I’m an accountant.", "Complementary expertise", "Work with us", "mailto:marcus@mysocialimpact.org?subject=Accountancy%20partnership"]].map(([title, meta, action, href], index) => <a key={title} href={href}><span>0{index + 1}</span><h3>{title}</h3><p>{meta}</p><strong>{action} →</strong><small>marcus@mysocialimpact.org</small></a>)}</div><ContactActions inverse /></div><div className="cir-signoff"><p>Measure what matters.<br />Learn what works.<br />Show the difference.</p><strong>My Social Impact</strong></div></section>
  </main><Footer /></>;
}
