"use client";
import { useEffect, useState } from "react";
import { highlights, type Report } from "./sorp-public-model";

const steps = ["Kick-off", "Current evidence", "Human review", "Action summary"];
const topics = [
  ["changes", "What has changed since publication?", "New programmes, leadership, strategy or reporting arrangements."],
  ["preparation", "Preparing for your next reporting period", "What is already underway, and what needs an owner or a deadline?"],
  ["evidence", "What can you evidence today?", "Current outcomes, learning, management information and unpublished reporting."],
  ["judgement", "Where would human judgement help?", "Proportionality, claims, interpretation and the conclusions you want to challenge."],
] as const;
export function SorpPublicDeepDive({ report, state, sessionId, onContextChange, onTenMinuteCall }: { report: Report; state: unknown; sessionId: string; onContextChange: (context: { notes: Record<string, string>; upload: string }) => void; onTenMinuteCall?: () => void }) {
  const [exploring, setExploring] = useState(false), [step, setStep] = useState(0);
  const [notes, setNotes] = useState<Record<string, string>>({}), [ready, setReady] = useState(false);
  const [upload, setUpload] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const key = `msi-sorp-deep-dive-prototype:${sessionId}`;
  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem(key) || "null"); if (stored) { setNotes(stored.notes || {}); setUpload(stored.upload || ""); } } catch { /* A prototype remains usable without local saving. */ } setReady(true); }, [key]);
  useEffect(() => { if (ready) try { localStorage.setItem(key, JSON.stringify({ notes, upload })); } catch { setError("These prototype notes could not be saved on this device. Keep a copy before leaving."); } }, [notes, upload, ready, key]);
  const priorities = highlights(report.tar).priorities;
  useEffect(() => { if (ready) onContextChange({ notes, upload }); }, [ready, notes, upload, onContextChange]);
  const mail = `mailto:marcus@mysocialimpact.org?subject=${encodeURIComponent(`SORP 2026 Current Readiness Deep-Dive — ${report.candidate.name}`)}&body=${encodeURIComponent(`Hello My Social Impact,\n\nI’d like to discuss a SORP 2026 Current Readiness Deep-Dive for ${report.candidate.name}.\n\nOur published-evidence review: TAR ${report.tar.score ?? "not scored"}/100; wider evidence ${report.wider.score ?? "not scored"}/100.\n\nPlease help us agree the scope, fee and a kick-off meeting.\n\nOur main concern:\n`)}`;
  async function reviewFile(file: File | undefined) {
    if (!file) return; setBusy(true); setError("");
    try { const form = new FormData(); form.append("file", file); form.append("state", JSON.stringify(state)); form.append("sessionId", sessionId); form.append("intelligenceVersion", report.intelligence.effectiveVersion); const response = await fetch("/api/readiness/report", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "The document could not be read.");
      const research = data.state?.organisationResearch?.selected?.publicReadiness;
      setUpload(`${file.name} — reviewed through the existing MSI evidence service. ${research?.widerEvidenceReason || data.assistant?.message || "Ready to discuss with MSI."}`);
      // The uploaded/current evidence is intentionally NOT copied into the free
      // public report or its state. This prototype is a separate local workspace.
    } catch (e) { setError(e instanceof Error ? e.message : "Upload failed. Please try again."); } finally { setBusy(false); }
  }
  return <section className="sp-deep">
    <p className="sp-kicker">SORP 2026 CURRENT READINESS DEEP-DIVE</p><h2>Where you actually are now.<br/>What to do next.</h2><p>Your free report looks at what you have published. The Deep-Dive looks at current practice, unpublished evidence, preparation for your next reporting period, human judgement and what still needs doing.</p>
    <ol className="sp-service-steps"><li><h3>A proper kick-off</h3><p>Meet MSI. Discuss what has changed, your concerns and where judgement is needed. Agree the scope and preparation.</p></li><li><h3>A current-evidence workspace</h3><p>Bring together current practice, supporting documents and gaps. Use the published review as a starting point, not a constraint.</p></li><li><h3>A final human review</h3><p>Challenge the conclusions with MSI, validate the evidence and work through proportionate reporting decisions.</p></li><li><h3>Your action summary</h3><p>A clear current-readiness position, agreed priorities and practical next actions.</p></li></ol>
    <div className="sp-service-actions"><a className="sp-button" href={mail}>BOOK / REQUEST MY DEEP-DIVE →</a><a className="sp-button sp-secondary" href="mailto:marcus@mysocialimpact.org?subject=SORP%2010-minute%20conversation" onClick={onTenMinuteCall}>NOT SURE? TALK TO US FOR 10 MINUTES →</a></div><p className="sp-small">We’ll agree the scope, fee and meeting times with you. This is an enquiry, not a confirmed booking or a payment. If cost is a barrier, tell us.</p><button className="sp-quiet" onClick={() => setExploring(v => !v)}>{exploring ? "CLOSE PROTOTYPE" : "EXPLORE THE DEEP-DIVE PROTOTYPE →"}</button>
    {exploring && <div className="sp-prototype"><p className="sp-notice"><b>Prototype workspace</b> · Try the proposed service journey. Notes are saved only on this device. No engagement, meeting or human review is created here. The free published report remains unchanged.</p><nav aria-label="Deep-Dive prototype steps">{steps.map((label, i) => <button key={label} className={step === i ? "" : "sp-secondary"} aria-current={step === i ? "step" : undefined} onClick={() => setStep(i)}>{i + 1}. {label}</button>)}</nav>
      {step === 0 && <div><h3>Your kick-off brief</h3><p>Start with what matters to your organisation. MSI uses this meeting to agree the focus, not to repeat the public homework.</p><label>What would make this engagement useful?<textarea value={notes.goals || ""} onChange={e => setNotes(n => ({ ...n, goals: e.target.value }))} placeholder="Your concerns, reporting deadline and what you want to leave with…"/></label><p className="sp-small">Meeting status: not booked. Use Request a kick-off to contact MSI.</p></div>}
      {step === 1 && <div><h3>Current practice. Fresh evidence.</h3>{topics.map(([id, label, hint]) => <label className="sp-note-field" key={id}>{label}<small>{hint}</small><textarea value={notes[id] || ""} onChange={e => setNotes(n => ({ ...n, [id]: e.target.value }))}/></label>)}<label className="sp-upload">Add a current report for MSI Intelligence to inspect<input type="file" accept=".pdf,.doc,.docx" disabled={busy} onChange={e => void reviewFile(e.target.files?.[0])}/></label><p className="sp-small">PDF or Word · up to 4 MB. Uses the existing document-reading service. The file is processed to extract evidence, not stored in a new document library. It will not change your free published-evidence score.</p>{busy && <p role="status">Reading your document…</p>}{upload && <p role="status" className="sp-notice">{upload}</p>}</div>}
      {step === 2 && <div><h3>Bring judgement into the room.</h3><p>In the final MSI meeting, challenge the findings, test the strength of claims and agree what is proportionate for your charity.</p><h4>Priorities to revisit from the published review</h4><ul>{priorities.map(f => <li key={f.fieldId}>{f.action}</li>)}</ul><label>Questions for the human review<textarea value={notes.review || ""} onChange={e => setNotes(n => ({ ...n, review: e.target.value }))}/></label><p className="sp-small">Human review status: not completed. Any current-readiness conclusion remains provisional until reviewed.</p></div>}
      {step === 3 && <div><p className="sp-kicker">DRAFT · NOT HUMAN-VALIDATED</p><h3>Your working action summary</h3><p><b>Current readiness:</b> not yet established. The paid engagement adds the evidence and human validation needed to reach that position.</p>{[["Your desired outcome", notes.goals], ["Changes since publication", notes.changes], ["Preparation and ownership", notes.preparation], ["Current evidence", notes.evidence], ["Judgement to resolve", notes.judgement], ["Human-review agenda", notes.review]].map(([title, text]) => <div key={title}><b>{title}</b><p>{text || "To agree with MSI."}</p></div>)}<h4>Starting priorities from the free review</h4><ol>{priorities.map(f => <li key={f.fieldId}>{f.action}</li>)}</ol><p>Where useful, the engagement can identify wider needs in purpose, leadership, data, delivery and communications—including Social Impact Excellence and the Social Impact Claims Code. No additional service is assumed.</p></div>}
      {error && <p role="alert" className="sp-error">{error}</p>}<div className="sp-service-actions">{step > 0 && <button className="sp-secondary" onClick={() => setStep(s => s - 1)}>← BACK</button>}{step < 3 && <button onClick={() => setStep(s => s + 1)}>CONTINUE TO {steps[step + 1].toUpperCase()} →</button>}</div>
    </div>}
  </section>;
}
