"use client";
import { useEffect, useRef, useState } from "react";
import { trackSorpEvent } from "./sorp-growth";
import { supportPence, type SupportChoice } from "./sorp-payment-amounts";
import { PUBLIC_BUILD, STORAGE_KEY, band, classificationLabel, highlights, methodology, emailResult, conversationReport, emptyLens, answerLabels, type Candidate, type Research, type Report, type Lens, type Finding, type Turn, type Intelligence } from "./sorp-public-model";
import { SorpPublicDeepDive } from "./sorp-public-deep-dive";
import "./sorp-public-review.css";

type Saved = { sessionId: string; state: unknown; candidate: Candidate | null; research: Research | null; report: Report | null; messages: Turn[]; intelligence: Intelligence | null; rating: number; comment: string; feedbackSent?: boolean; emailSent: boolean };
const sorpSource = "https://www.charitysorp.org/documents/d/guest/charities-sorp-2026-1";
async function post(url: string, body: unknown) { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok || data.error) throw new Error(data.error || "We couldn’t complete that request. Please try again."); return data; }
function SourceLink({ url, children }: { url: string; children: React.ReactNode }) { return /^https:\/\//.test(url) ? <a href={url} target="_blank" rel="noreferrer">{children} ↗</a> : <span>{children}</span>; }
function FindingRow({ finding: f }: { finding: Finding }) { return <details className="sp-finding"><summary><span className="sp-tag">{classificationLabel(f.classification)}</span><span>{f.finding}<small>{answerLabels[f.answer]} · {f.confidence} confidence</small></span><span aria-hidden="true">+</span></summary><div className="sp-trace"><p className="sp-kicker">WHY ARE YOU SAYING THIS?</p><b>What MSI concludes</b><p>{f.reason}</p><b>Evidence used</b><p>{f.excerpt ? `“${f.excerpt}”` : "Not established in the material we could inspect. This does not prove the practice is absent."}</p><p className="sp-small"><SourceLink url={f.sourceUrl}>{f.page ? `Source · ${f.page}` : "Evidence source"}</SourceLink></p><b>What SORP says</b>{f.sources.map(s => <div key={s.reference}><p className="sp-small"><SourceLink url={`${sorpSource}#page=${s.page}`}>SORP 2026 · {s.reference} · p.{s.page}</SourceLink></p><blockquote>{s.text}</blockquote></div>)}{["JUDGEMENT", "MSI_READINESS"].includes(f.classification) && <p className="sp-small">MSI judgement is not an official fourth SORP category.</p>}<b>Useful next action</b><p>{f.action}</p></div></details>; }
function LensScore({ lens, title }: { lens: Lens; title: string }) { return <div className={`sp-score sp-score-${lens.lens}`}><p className="sp-kicker">{title}</p><div><strong>{lens.score ?? "—"}</strong>{lens.score !== null && <span>/100</span>}<h3>{band(lens.score)}</h3></div><p className="sp-small">Evidence confidence: <b>{lens.confidence}</b></p><p>{lens.lens === "tar" ? "Based only on the latest submitted Trustees’ Annual Report / statutory reporting we could inspect." : "A separate view of additional published evidence: Impact Report, website and other public material. No TAR evidence contributes to this score."}</p>{lens.limitation && <p className="sp-small">{lens.limitation}</p>}</div>; }

export function SorpPublicReview() {
  const [saved, setSaved] = useState<Saved>({ sessionId: "", state: null, candidate: null, research: null, report: null, messages: [], intelligence: null, rating: 0, comment: "", emailSent: false });
  const [loaded, setLoaded] = useState(false), [query, setQuery] = useState(""), [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(""), [error, setError] = useState(""), [progress, setProgress] = useState<string[]>([]), [chatOpen, setChatOpen] = useState(false);
  const [panel, setPanel] = useState<"email" | "support" | "deep" | null>(null);
  const [email, setEmail] = useState(""), [name, setName] = useState(""), [role, setRole] = useState("");
  const [prototypeContext, setPrototypeContext] = useState<{ notes: Record<string, string>; upload: string }>({ notes: {}, upload: "" });
  const [support, setSupport] = useState<SupportChoice>(5), [custom, setCustom] = useState("");
  const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder | null>(null), media = useRef<MediaStream | null>(null);
  const chatEnd = useRef<HTMLDivElement>(null), panelRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null"); if (stored?.sessionId) setSaved(stored); else setSaved(s => ({ ...s, sessionId: crypto.randomUUID() })); }
    catch { setSaved(s => ({ ...s, sessionId: crypto.randomUUID() })); setError("Device saving is unavailable. Keep this page open, or email your report when it is ready."); }
    setLoaded(true); return () => { media.current?.getTracks().forEach(track => track.stop()); };
  }, []);
  useEffect(() => { if (loaded) try { localStorage.setItem(STORAGE_KEY, JSON.stringify(saved)); } catch { setError("Your device could not save this review. Keep the page open and email the report to keep a copy."); } }, [saved, loaded]);
  useEffect(() => { if (chatOpen) chatEnd.current?.scrollIntoView({ block: "nearest" }); }, [saved.messages, chatOpen]);
  useEffect(() => { if (panel) panelRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [panel]);
  useEffect(() => { if (busy === "build" || saved.report) window.scrollTo({ top: 0, behavior: "instant" }); }, [busy === "build", saved.report?.createdAt]);
  function event(type: string, extra = {}) { void trackSorpEvent(saved.sessionId, type, { organisation: saved.candidate?.name, readinessScore: saved.report?.tar.score ?? undefined, ...extra }, false); }
  async function find() {
    if (!query.trim() || busy) return; setBusy("search"); setError(""); event("assessment_started");
    try { const data = await post("/api/published-review", { operation: "find", query: [saved.research?.query, query].filter(Boolean).join("; Additional clue: "), sessionId: saved.sessionId, intelligencePin: saved.intelligence }); setSaved(s => ({ ...s, research: data.research, intelligence: data.intelligence })); event("organisation_found"); }
    catch (e) { setError(e instanceof Error ? e.message : "Search failed. Please try again."); } finally { setBusy(""); }
  }
  async function build(candidate: Candidate) {
    if (busy) return; setBusy("build"); setError(""); setProgress(["Organisation confirmed"]); event("organisation_confirmed"); setSaved(s => ({ ...s, candidate }));
    try {
      const profile = await post("/api/published-review", { operation: "profile", candidate, sessionId: saved.sessionId, intelligencePin: saved.intelligence });
      setSaved(s => ({ ...s, candidate: profile.candidate, state: profile.state, intelligence: profile.intelligence })); setProgress(p => [...p, "Latest public sources located"]);
      const getLens = async (lens: "tar" | "wider") => { try { const data = await post("/api/published-review", { operation: lens, candidate: profile.candidate, state: profile.state, sessionId: saved.sessionId, intelligencePin: profile.intelligence }); setProgress(p => [...p, lens === "tar" ? "Statutory reporting assessed" : "Wider evidence assessed separately"]); return data.lens as Lens; } catch (e) { return emptyLens(lens, e instanceof Error ? e.message : "This evidence could not be assessed."); } };
      const [tar, wider] = await Promise.all([getLens("tar"), getLens("wider")]);
      setSaved(s => ({ ...s, report: { candidate: profile.candidate, tar, wider, createdAt: new Date().toISOString(), intelligence: profile.intelligence }, emailSent: false })); event("report_opened");
    } catch (e) { setError(e instanceof Error ? e.message : "The public review could not finish. Please retry."); } finally { setBusy(""); }
  }
  async function sendMessage() {
    if (!draft.trim() || busy) return; const message = draft.trim(); setBusy("chat"); setError(""); const messages: Turn[] = [...saved.messages, { role: "user", content: message }]; setSaved(s => ({ ...s, messages })); setDraft("");
    try { const data = await post("/api/readiness", { message, state: saved.state, history: saved.messages.slice(-40), sessionId: saved.sessionId, intelligencePin: saved.intelligence, surface: panel === "deep" ? "current_readiness_prototype" : "published_evidence", displayedReport: { ...conversationReport(saved.report), ...(panel === "deep" ? { currentReadinessPrototype: prototypeContext } : {}) } }); setSaved(s => ({ ...s, state: data.state, intelligence: data.intelligence, research: s.report ? s.research : data.state.organisationResearch, messages: [...messages, { role: "assistant", content: data.assistant.message, citations: data.assistant.citations }] })); }
    catch (e) { setDraft(message); setError(e instanceof Error ? e.message : "Please try sending again."); } finally { setBusy(""); }
  }
  async function microphone() {
    if (recording) { recorder.current?.stop(); setRecording(false); return; }
    try {
      if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") throw new Error("Voice isn’t available in this browser. You can still type your question.");
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); media.current = stream; const mimeType = ["audio/webm;codecs=opus", "audio/mp4", "audio/webm"].find(type => MediaRecorder.isTypeSupported(type));
      const rec = mimeType ? new MediaRecorder(stream, { mimeType }) : new MediaRecorder(stream); recorder.current = rec; const chunks: Blob[] = [];
      rec.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
      rec.onstop = () => { stream.getTracks().forEach(t => t.stop()); void (async () => { setBusy("voice"); try { const form = new FormData(); form.append("audio", new Blob(chunks, { type: rec.mimeType }), rec.mimeType.includes("mp4") ? "question.m4a" : "question.webm"); const response = await fetch("/api/readiness/transcribe", { method: "POST", body: form }); const data = await response.json(); if (!response.ok || !data.transcript) throw new Error(data.error || "We couldn’t transcribe that. Please try again."); setDraft(v => [v, data.transcript].filter(Boolean).join(" ")); } catch (e) { setError(e instanceof Error ? e.message : "Voice transcription failed."); } finally { setBusy(""); } })(); };
      rec.start(250); setRecording(true); setError("");
    } catch (e) { setError(e instanceof Error ? e.message : "Microphone access wasn’t available."); }
  }
  async function sendEmail(e: React.FormEvent) {
    e.preventDefault(); if (!saved.report || busy) return; setBusy("email"); setError(""); event("email_report_requested");
    try { const data = await post("/api/readiness/report-email", { sessionId: saved.sessionId, email, name, role, shareRequestWithMsi: true, organisation: saved.candidate?.name, result: emailResult(saved.report), impactMode: saved.candidate?.entityType !== "registered_charity" }); if (!data.ok || !data.attachment?.endsWith(".pdf")) throw new Error("The full PDF was not confirmed as attached. Please retry."); setSaved(s => ({ ...s, emailSent: true })); event("report_emailed"); }
    catch (e) { setError(e instanceof Error ? e.message : "Email failed. No success was confirmed."); } finally { setBusy(""); }
  }
  async function saveFeedback() {
    if (busy) return; setBusy("feedback"); setError("");
    try { await post("/api/published-review", { operation: "feedback", sessionId: saved.sessionId, organisation: saved.candidate?.name, rating: saved.rating, comment: saved.comment }); setSaved(s => ({ ...s, feedbackSent: true })); }
    catch (e) { setError(e instanceof Error ? e.message : "Feedback could not be sent. Your report is unaffected."); } finally { setBusy(""); }
  }
  async function contribute() {
    const amountMinor = supportPence(support, custom); if (!amountMinor || busy) return; setBusy("support"); setError(""); event("support_payment_started", { amountMinor, currency: "GBP", paymentType: "voluntary_support" });
    try { const data = await post("/api/sorp-payments/checkout", { paymentType: "voluntary_support", band: null, amountMinor, sessionId: saved.sessionId, organisation: saved.candidate?.name, idempotencyKey: `${saved.sessionId}:support:${amountMinor}:${crypto.randomUUID()}` }); const url = new URL(data.url); if (url.hostname !== "checkout.stripe.com") throw new Error("Secure checkout could not be opened."); window.location.assign(url.href); }
    catch (e) { setError(e instanceof Error ? e.message : "Please try again."); setBusy(""); }
  }
  const report = saved.report, summary = report ? highlights(report.tar) : null, candidates = saved.research?.candidates || [];
  return <div className="sorp-public">
    <header className="sp-header"><a href="/">MY SOCIAL IMPACT</a><span>Are You SORP Ready?</span><small>{report ? saved.candidate?.name : "Published evidence. Clear next steps."}</small></header>
    <main className="sp-main">
      {busy === "build" ? <section className="sp-generation" aria-live="polite"><p className="sp-kicker">YOUR PUBLIC-EVIDENCE REVIEW</p><h1>The homework<br/>is happening.</h1><p>Reading the published evidence. Comparing it with SORP. Bringing your priorities into focus.</p><ul>{["Organisation confirmed", "Latest public sources located", "Statutory reporting assessed", "Wider evidence assessed separately"].map(step => <li key={step} className={progress.includes(step) ? "is-done" : ""}>{progress.includes(step) ? "✓" : "—"} {step}</li>)}</ul><div className="sp-brand-moment"><h2>SORP is the requirement.<br/><em>Better impact is the opportunity.</em></h2><p>Better evidence helps charities understand what works, learn what doesn’t, make better decisions, improve delivery and communicate with confidence.</p><small>BUILT WITH THE IDEAS SHED<br/>Useful digital tools for charities and purpose-led organisations. More tools are coming.</small></div></section>
      : !report ? <section className="sp-entry"><div><p className="sp-kicker">YOUR FREE PUBLISHED-EVIDENCE REVIEW</p><h1>Are you<br/>SORP ready?</h1><p className="sp-lead">Let’s see what your latest reporting tells us.</p><p>We’ll find your charity, read the public evidence and show you what looks strong, what needs attention and why.</p><form onSubmit={e => { e.preventDefault(); void find(); }} className="sp-search"><label htmlFor="charity-query">{saved.research ? "Refine the search with a name, number or website" : "Your charity’s name, number or website"}</label><input id="charity-query" value={query} onChange={e => setQuery(e.target.value)} placeholder="Start with your charity…" required/><button disabled={!!busy || !query.trim()}>{busy === "search" ? "SEARCHING…" : "FIND MY CHARITY →"}</button></form><p className="sp-small">Full review and report included. No card. No email required.</p>
        {busy === "search" && <p role="status" className="sp-notice">Searching for your charity. Hang on a moment…</p>}
        {saved.research && !candidates.length && <p className="sp-notice">We haven’t found a reliable match yet. Add the charity number, its website, or where it works to narrow the search.</p>}
        {candidates.map(c => <article className="sp-candidate" key={c.officialUrl + c.name}><p className="sp-kicker">IS THIS YOUR ORGANISATION?</p><h2>{c.name}</h2><p>{c.registrationNumber && `Registration ${c.registrationNumber} · `}{c.locality}</p><p>{c.summary}</p><p className="sp-small"><SourceLink url={c.officialUrl}>Official record</SourceLink>{" · "}<SourceLink url={c.website}>Website</SourceLink></p><button disabled={!!busy} onClick={() => void build(c)}>YES — REVIEW THIS ORGANISATION →</button></article>)}
        {saved.candidate && !candidates.length && <button disabled={!!busy} onClick={() => void build(saved.candidate!)}>RETRY {saved.candidate.name}’S REVIEW →</button>}
      </div><aside className="sp-entry-note"><span className="sp-kicker">THE HOMEWORK IS OURS.</span><h2>The evidence.<br/>The requirements.<br/>Your next move.</h2><div><b>01 / Real public evidence</b><p>Your Trustees’ Annual Report and accounts. Impact reports and website evidence, kept separate.</p></div><div><b>02 / SORP as the source of truth</b><p>See the requirement, the evidence and the reasoning behind each important finding.</p></div><div><b>03 / A useful answer, not a questionnaire</b><p>A retrospective starting point—not a claim to know everything happening in your charity today.</p></div></aside></section>
      : <article className="sp-report">
        <div className="sp-report-heading"><div><p className="sp-kicker">YOUR FREE REPORT · PUBLISHED EVIDENCE</p><h1>Here’s where<br/>you stand.</h1><p className="sp-lead">{report.candidate.name}</p></div><div className="sp-report-meta"><p>{report.tar.period || report.candidate.reportPeriod || "Latest published reporting"}</p><p className="sp-small">Prepared {new Date(report.createdAt).toLocaleDateString("en-GB")}<br/>Narrative & impact-reporting readiness</p><button className="sp-secondary" onClick={() => window.print()}>PRINT / SAVE PDF</button></div></div>
        <p className="sp-scope">A look back at your published evidence—not a verdict on everything you do today, and not a certificate of full SORP compliance.</p>
        {(report.candidate.entityType !== "registered_charity" || report.tar.accountingBasis === "receipts") && <p className="sp-notice">SORP may not apply to this entity or accounting basis. Treat the following as wider narrative-reporting guidance, not statutory requirements for this organisation. Ask MSI about your circumstances.</p>}
        <div className="sp-scores"><LensScore lens={report.tar} title="TRUSTEES’ ANNUAL REPORT READINESS"/><LensScore lens={report.wider} title="WIDER EVIDENCE VIEW"/></div><p className="sp-distinction">Wider evidence can show stronger organisational practice. It does not automatically satisfy what should be reported in the Trustees’ Annual Report.</p>
        {(!report.tar.readable || !report.wider.readable) && <div className="sp-notice"><p>Some source material could not be assessed. The report below makes that gap explicit; no score has been invented for unread evidence.</p><button className="sp-secondary" disabled={!!busy} onClick={() => void build(report.candidate)}>RETRY PUBLIC EVIDENCE</button></div>}
        <section className="sp-summary"><div><p className="sp-kicker">FROM YOUR STATUTORY REPORT</p><h2>What looks strong</h2>{summary!.strong.length ? summary!.strong.map(f => <FindingRow key={f.fieldId} finding={f}/>) : <p>No clear strengths could be established from the statutory material inspected.</p>}</div><div><p className="sp-kicker">WHERE TO FOCUS</p><h2>Most important gaps</h2>{summary!.gaps.length ? summary!.gaps.map(f => <FindingRow key={f.fieldId} finding={f}/>) : <p>{report.tar.readable ? "No major gap was identified in the scored narrative fields. This is not a complete compliance audit." : "Access to the statutory report is the first evidence gap to resolve."}</p>}</div></section>
        <section className="sp-priorities"><p className="sp-kicker">YOUR NEXT MOVE</p><h2>Start here.</h2><ol>{summary!.priorities.map(f => <li key={f.fieldId}><span className="sp-tag">{classificationLabel(f.classification)}</span><p>{f.action}</p></li>)}{!summary!.priorities.length && <li><p>{report.tar.readable ? "Review these conclusions with your trustees and use the evidence trail to prepare your next report." : "Locate a readable copy of the latest statutory report before drawing a readiness conclusion."}</p></li>}</ol></section>
        <section className="sp-evidence"><p className="sp-kicker">THE FULL EVIDENCE TRAIL</p><h2>No black box.</h2><p>Open any finding to see the SORP source, the evidence, MSI’s reasoning and confidence.</p><div className="sp-legend"><p><b>MUST</b> Required by SORP.</p><p><b>SHOULD</b> Recommended by SORP.</p><p><b>MAY</b> Optional/permitted by SORP.</p><p><b>MSI JUDGEMENT</b> Context, evidence and proportionality—not an official fourth SORP category.</p></div>
          {[report.tar, report.wider].map(lens => <section key={lens.lens} className="sp-lens-detail"><h3>{lens.lens === "tar" ? "Trustees’ Annual Report · statutory evidence only" : "Wider evidence · website & impact reporting"}</h3><p className="sp-small"><SourceLink url={lens.sourceUrl}>{lens.title}</SourceLink> {lens.period}</p>{lens.findings.map(f => <FindingRow key={f.fieldId} finding={f}/>)}</section>)}
          <details className="sp-method"><summary>Methodology, scope & known limits</summary><p>{methodology}</p><p>This focuses on SORP’s narrative and impact-reporting requirements. Financial reporting modules and conditional checks—including fundraising, group reporting and sustainability—may need separate review. No MAY gap is implied merely because an optional disclosure is absent.</p><p>Latest published income: {report.candidate.latestIncome === null ? "not established" : new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(report.candidate.latestIncome)}. Accounting basis: {report.tar.accountingBasis === "unknown" ? "not established by the direct document review" : `${report.tar.accountingBasis} accounts, observed in the statutory document`}. Reporting period: {report.tar.period || "not established"}.</p><SourceLink url={sorpSource}>Read the authoritative SORP 2026</SourceLink></details>
        </section>
        <section className="sp-judgement"><p className="sp-kicker">WHERE HUMAN JUDGEMENT HELPS</p><h2>The evidence is a starting point.</h2>{report.tar.findings.filter(f => ["JUDGEMENT", "MSI_READINESS"].includes(f.classification)).slice(0, 3).map(f => <p key={f.fieldId}>{f.reason}</p>)}<p>What has changed since publication? Is your evidence proportionate? Which claims can you stand behind? These need current context, not another automatic score.</p></section>
        <section className="sp-feedback"><div><p className="sp-kicker">ONE QUICK, OPTIONAL QUESTION</p><h2>How’s this going?</h2><p>We want this to be genuinely useful for charities. A quick rating or comment helps us improve it.</p></div><div><div className="sp-stars" aria-label="How useful was this?">{[1, 2, 3, 4, 5].map(value => <button key={value} aria-label={`${value} out of 5`} aria-pressed={saved.rating === value} onClick={() => { setSaved(s => ({ ...s, rating: value, feedbackSent: false })); event("quick_review_feedback_submitted", { rating: value }); }}>{value <= saved.rating ? "★" : "☆"}</button>)}</div><p className="sp-small">1 = Not useful yet · 5 = Extremely useful</p><label htmlFor="sp-comment">Optional comment</label><textarea id="sp-comment" value={saved.comment} onChange={e => setSaved(s => ({ ...s, comment: e.target.value, feedbackSent: false }))} maxLength={2000} placeholder="Anything we could improve?"/><button className="sp-secondary" disabled={!!busy || (!saved.rating && !saved.comment.trim()) || saved.feedbackSent} onClick={() => void saveFeedback()}>{saved.feedbackSent ? "SENT — THANK YOU ✓" : busy === "feedback" ? "SENDING…" : "SEND OPTIONAL FEEDBACK"}</button><p className="sp-small">Your report is already yours. Feedback is never required. Comments are sent to MSI.</p></div></section>
        <section className="sp-next"><div><p className="sp-kicker">OPTIONAL · THE CURRENT-READINESS DEEP-DIVE</p><h2>That’s what you published.<br/>Where are you now?</h2><p>Work with My Social Impact on what has changed, your next reporting period and what still needs doing. Current evidence, a deeper diagnostic and human judgement—with a kick-off meeting, final human review and concise action summary.</p></div><button onClick={() => { setPanel("deep"); event("human_review_selected"); }}>EXPLORE THE DEEP-DIVE →</button></section>
      </article>}
      {error && <p role="alert" className="sp-error">{error}</p>}
      {panel && report && <div ref={panelRef} className="sp-panel"><button className="sp-secondary sp-close" onClick={() => setPanel(null)}>CLOSE ×</button>{panel === "email" ? <><h2>Keep your full report.</h2><p>We’ll attach the complete PDF. You’ll stay right here.</p>{saved.emailSent ? <p role="status" className="sp-notice">SENT ✓ Your full PDF has been sent. Your review and next actions are still here.</p> : <form onSubmit={sendEmail} className="sp-email-form"><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></label><label>Name <small>(optional)</small><input value={name} onChange={e => setName(e.target.value)}/></label><label>Role <small>(optional)</small><input value={role} onChange={e => setRole(e.target.value)}/></label><p className="sp-small">We’ll email your full PDF and share a copy of your request with My Social Impact, including any name and role you choose to add. No account or marketing subscription.</p><button disabled={!!busy}>{busy === "email" ? "SENDING FULL PDF…" : "EMAIL MY PDF →"}</button></form>}</> : panel === "support" ? <><h2>Help keep this free.</h2><p>A voluntary contribution helps us keep improving useful tools for charities.</p><div className="sp-amounts">{([5, 10, 20, "other"] as const).map(amount => <button key={amount} className={support === amount ? "" : "sp-secondary"} onClick={() => setSupport(amount)}>{amount === "other" ? "Another amount" : `£${amount}`}</button>)}</div>{support === "other" && <label>Amount in pounds (£1–£1,000)<input inputMode="decimal" value={custom} onChange={e => setCustom(e.target.value)}/></label>}<button disabled={!!busy || !supportPence(support, custom)} onClick={() => void contribute()}>{busy === "support" ? "OPENING SECURE CHECKOUT…" : "CONTINUE TO SECURE CHECKOUT →"}</button><p className="sp-small">Opens the existing secure Stripe payment page. Your report is saved on this device.</p></> : <SorpPublicDeepDive report={report} state={saved.state} sessionId={saved.sessionId} onContextChange={setPrototypeContext}/>}</div>}
      <footer className="sp-version">{PUBLIC_BUILD}{saved.intelligence && <details><summary>MSI Intelligence · {saved.intelligence.effectiveVersion}</summary>{saved.intelligence.layers.map(layer => <p key={layer.name}>{layer.name} · {layer.label}</p>)}</details>}</footer>
    </main>
    {chatOpen && <aside className="sp-chat" aria-label="Ask My Social Impact"><div className="sp-chat-head"><b>Ask My Social Impact</b><button className="sp-secondary" onClick={() => setChatOpen(false)} aria-label="Close conversation">×</button></div><div className="sp-chat-history">{!saved.messages.length && <p>Ask about the evidence, a SORP requirement, or what this means for your charity.</p>}{saved.messages.map((m, i) => <div key={i} className={`sp-message sp-${m.role}`}><small>{m.role === "user" ? "YOU" : "MY SOCIAL IMPACT INTELLIGENCE"}</small><p>{m.content}</p>{m.citations?.map(c => <details key={c.reference}><summary>SORP {c.reference}</summary><p>{c.extract}</p></details>)}</div>)}{busy === "chat" && <p role="status">Thinking about your question…</p>}<div ref={chatEnd}/></div>{error && <p role="alert" className="sp-error">{error}</p>}<form onSubmit={e => { e.preventDefault(); void sendMessage(); }}><label htmlFor="sp-chat-input">Your question or context</label><textarea id="sp-chat-input" value={draft} onChange={e => setDraft(e.target.value)} maxLength={4000}/><div><button type="button" className="sp-secondary" disabled={!!busy} onClick={() => void microphone()}>{recording ? "STOP RECORDING" : "USE MICROPHONE"}</button><button disabled={!!busy || !draft.trim() || recording}>{busy === "voice" ? "TRANSCRIBING…" : "SEND →"}</button></div></form></aside>}
    <div className="sp-actionbar">{report ? <><button className="sp-secondary" onClick={() => setPanel("email")}>{saved.emailSent ? "SENT ✓" : "EMAIL MY PDF →"}</button><button onClick={() => { setPanel("deep"); event("human_review_selected"); }}>BOOK A SORP 2026 DEEP-DIVE →</button><button className="sp-quiet" onClick={() => { setPanel("support"); event("support_selected"); }}>SUPPORT THE FREE TOOL</button></> : <span className="sp-small">Your charity. Its real evidence. A useful first answer.</span>}<button className="sp-secondary" onClick={() => setChatOpen(v => !v)}>{chatOpen ? "CLOSE CHAT" : "ASK MSI"}</button></div>
  </div>;
}
