"use client";
import { useEffect, useRef, useState } from "react";
import { trackSorpEvent } from "./sorp-growth";
import { supportPence, type SupportChoice } from "./sorp-payment-amounts";
import { PUBLIC_BUILD, STORAGE_KEY, band, classificationLabel, highlights, methodology, emailResult, conversationReport, emptyLens, answerLabels, type Candidate, type Research, type Report, type Lens, type Finding, type Turn, type Intelligence } from "./sorp-public-model";
import { SorpPublicDeepDive } from "./sorp-public-deep-dive";
import "./sorp-public-review.css";

type Step = "organisation" | "evidence" | "snapshot" | "quick-feedback" | "changed" | "generating" | "report" | "final-feedback" | "next" | "non-sorp";
type Saved = { sessionId: string; state: unknown; candidate: Candidate | null; research: Research | null; report: Report | null; messages: Turn[]; intelligence: Intelligence | null; step?: Step; email?: string; name?: string; role?: string; rating: number; comment: string; finalRating?: number; finalComment?: string; feedbackSent?: boolean; emailSent: boolean; supportDeclined?: boolean };
const steps: { step: Step; label: string }[] = [{ step: "organisation", label: "ORGANISATION" }, { step: "evidence", label: "EVIDENCE" }, { step: "snapshot", label: "SNAPSHOT" }, { step: "changed", label: "WHAT’S CHANGED?" }, { step: "report", label: "REPORT" }];
const sorpSource = "https://www.charitysorp.org/documents/d/guest/charities-sorp-2026-1";
async function post(url: string, body: unknown) { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok || data.error) throw new Error(data.error || "We couldn’t complete that request. Please try again."); return data; }
function SourceLink({ url, children }: { url: string; children: React.ReactNode }) { return /^https:\/\//.test(url) ? <a href={url} target="_blank" rel="noreferrer">{children} ↗</a> : <span>{children}</span>; }
function FindingRow({ finding: f }: { finding: Finding }) { return <details className="sp-finding"><summary><span className="sp-tag">{classificationLabel(f.classification)}</span><span>{f.finding}<small>{answerLabels[f.answer]} · {f.confidence} confidence · Why are you saying this? →</small></span><span aria-hidden="true">+</span></summary><div className="sp-trace"><p className="sp-kicker">WHY ARE YOU SAYING THIS?</p><b>What MSI concludes</b><p>{f.reason}</p><b>Evidence used</b><p>{f.excerpt ? `“${f.excerpt}”` : "Not established in the material we could inspect. This does not prove the practice is absent."}</p><p className="sp-small"><SourceLink url={f.sourceUrl}>{f.page ? `Source · ${f.page}` : "Evidence source"}</SourceLink></p><b>What SORP says</b>{f.sources.map(s => <div key={s.reference}><p className="sp-small"><SourceLink url={`${sorpSource}#page=${s.page}`}>SORP 2026 · {s.reference} · p.{s.page}</SourceLink></p><blockquote>{s.text}</blockquote></div>)}{["JUDGEMENT", "MSI_READINESS"].includes(f.classification) && <p className="sp-small">MSI judgement is not an official fourth SORP category.</p>}<b>Useful next action</b><p>{f.action}</p></div></details>; }
function LensScore({ lens, title }: { lens: Lens; title: string }) { return <div className={`sp-score sp-score-${lens.lens}`}><p className="sp-kicker">{title}</p><div><strong>{lens.score ?? "—"}</strong>{lens.score !== null && <span>/100</span>}<h3>{band(lens.score)}</h3></div><p className="sp-small">Evidence confidence: <b>{lens.confidence}</b></p><p>{lens.lens === "tar" ? "Based only on the latest submitted Trustees’ Annual Report / statutory reporting we could inspect." : "A separate view of additional published evidence: Impact Report, website and other public material. No TAR evidence contributes to this score."}</p>{lens.limitation && <p className="sp-small">{lens.limitation}</p>}</div>; }

export function SorpPublicReview() {
  const [saved, setSaved] = useState<Saved>({ sessionId: "", state: null, candidate: null, research: null, report: null, messages: [], intelligence: null, step: "organisation", rating: 0, comment: "", emailSent: false });
  const [loaded, setLoaded] = useState(false), [query, setQuery] = useState(""), [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(""), [error, setError] = useState(""), [progress, setProgress] = useState<string[]>([]), [chatOpen, setChatOpen] = useState(false);
  const [panel, setPanel] = useState<"email" | "support" | "deep" | null>(null);
  const [email, setEmail] = useState(""), [name, setName] = useState(""), [role, setRole] = useState("");
  const [prototypeContext, setPrototypeContext] = useState<{ notes: Record<string, string>; upload: string }>({ notes: {}, upload: "" });
  const [support, setSupport] = useState<SupportChoice>(5), [custom, setCustom] = useState("");
  const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder | null>(null), media = useRef<MediaStream | null>(null);
  const chatEnd = useRef<HTMLDivElement>(null), panelRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null"); if (stored?.sessionId) { setSaved({ ...stored, step: stored.step || (stored.report ? "report" : stored.candidate ? "evidence" : "organisation") }); setEmail(stored.email || ""); setName(stored.name || ""); setRole(stored.role || ""); } else setSaved(s => ({ ...s, sessionId: crypto.randomUUID() })); }
    catch { setSaved(s => ({ ...s, sessionId: crypto.randomUUID() })); setError("Device saving is unavailable. Keep this page open, or email your report when it is ready."); }
    setLoaded(true); return () => { media.current?.getTracks().forEach(track => track.stop()); };
  }, []);
  useEffect(() => { if (loaded) try { localStorage.setItem(STORAGE_KEY, JSON.stringify(saved)); } catch { setError("Your device could not save this review. Keep the page open and email the report to keep a copy."); } }, [saved, loaded]);
  useEffect(() => { if (chatOpen) chatEnd.current?.scrollIntoView({ block: "nearest" }); }, [saved.messages, chatOpen]);
  useEffect(() => { if (panel) panelRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [panel]);
  useEffect(() => { window.scrollTo({ top: 0, behavior: "instant" }); }, [saved.step]);
  function event(type: string, extra = {}) { void trackSorpEvent(saved.sessionId, type, { organisation: saved.candidate?.name, readinessScore: saved.report?.tar.score ?? undefined, ...extra }, false); }
  function go(step: Step) { setPanel(null); setSaved(s => ({ ...s, step })); event("stage_viewed", { currentStage: steps.findIndex(item => item.step === step) + 1 }); }
  async function find() {
    if (!query.trim() || busy) return; setBusy("search"); setError(""); event("assessment_started");
    try { const data = await post("/api/published-review", { operation: "find", query: [saved.research?.query, query].filter(Boolean).join("; Additional clue: "), sessionId: saved.sessionId, intelligencePin: saved.intelligence }); setSaved(s => ({ ...s, research: data.research, intelligence: data.intelligence })); event("organisation_found"); }
    catch (e) { setError(e instanceof Error ? e.message : "Search failed. Please try again."); } finally { setBusy(""); }
  }
  async function confirm(candidate: Candidate) {
    if (busy) return; setBusy("profile"); setError(""); event("organisation_confirmed"); setSaved(s => ({ ...s, candidate }));
    try {
      const profile = await post("/api/published-review", { operation: "profile", candidate, sessionId: saved.sessionId, intelligencePin: saved.intelligence });
      setSaved(s => ({ ...s, candidate: profile.candidate, state: profile.state, intelligence: profile.intelligence, step: "evidence" }));
    } catch (e) { setError(e instanceof Error ? e.message : "We couldn’t inspect this organisation yet. Please retry."); } finally { setBusy(""); }
  }
  async function buildReview(e?: React.FormEvent) {
    e?.preventDefault(); if (!saved.candidate || !saved.intelligence || busy || !email.trim()) return;
    setBusy("build"); setError(""); setProgress(["Bringing together your public evidence"]); setSaved(s => ({ ...s, email: email.trim(), name: name.trim(), role, step: "generating" })); event("email_captured");
    try {
      const profile = { candidate: saved.candidate, state: saved.state, intelligence: saved.intelligence };
      const getLens = async (lens: "tar" | "wider") => { try { const data = await post("/api/published-review", { operation: lens, candidate: profile.candidate, state: profile.state, sessionId: saved.sessionId, intelligencePin: profile.intelligence }); setProgress(p => [...p, lens === "tar" ? "Statutory reporting assessed" : "Wider evidence assessed separately"]); return data.lens as Lens; } catch (e) { return emptyLens(lens, e instanceof Error ? e.message : "This evidence could not be assessed."); } };
      const [tar, wider] = await Promise.all([profile.candidate.entityType === "registered_charity" ? getLens("tar") : Promise.resolve(emptyLens("tar", "SORP is not a compliance requirement for this entity.")), getLens("wider")]);
      setSaved(s => ({ ...s, report: { candidate: profile.candidate, tar, wider, createdAt: new Date().toISOString(), intelligence: profile.intelligence }, step: profile.candidate.entityType === "registered_charity" ? "snapshot" : "non-sorp", emailSent: false })); event("public_research_completed", { readinessScore: tar.score ?? undefined, evidenceConfidence: tar.confidence }); event("snapshot_viewed", { readinessScore: tar.score ?? undefined, evidenceConfidence: tar.confidence }); event("tar_score", { readinessScore: tar.score ?? undefined, evidenceConfidence: tar.confidence }); event("wider_evidence_score", { readinessScore: wider.score ?? undefined, evidenceConfidence: wider.confidence }); if (profile.candidate.entityType !== "registered_charity") event("non_sorp_identified");
    } catch (e) { setSaved(s => ({ ...s, step: "evidence" })); setError(e instanceof Error ? e.message : "The public review could not finish. Please retry."); } finally { setBusy(""); }
  }
  async function sendMessage() {
    if (!draft.trim() || busy) return; const message = draft.trim(); setBusy("chat"); setError(""); if (saved.step === "changed") event("guided_conversation_started"); const messages: Turn[] = [...saved.messages, { role: "user", content: message }]; setSaved(s => ({ ...s, messages })); setDraft("");
    try { const data = await post("/api/readiness", { message, state: saved.state, history: saved.messages.slice(-40), sessionId: saved.sessionId, intelligencePin: saved.intelligence, surface: panel === "deep" ? "current_readiness_prototype" : "published_evidence", displayedReport: { ...conversationReport(saved.report), ...(panel === "deep" ? { currentReadinessPrototype: prototypeContext } : {}) } }); setSaved(s => ({ ...s, state: data.state, intelligence: data.intelligence, research: s.report ? s.research : data.state.organisationResearch, messages: [...messages, { role: "assistant", content: data.assistant.message, citations: data.assistant.citations }] })); }
    catch (e) { setDraft(message); setError(e instanceof Error ? e.message : "Please try sending again."); } finally { setBusy(""); }
  }
  async function microphone() {
    if (recording) { recorder.current?.stop(); setRecording(false); return; }
    try {
      if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") throw new Error("Voice isn’t available in this browser. You can still type your question.");
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); media.current = stream; const mimeType = ["audio/webm;codecs=opus", "audio/mp4", "audio/webm"].find(type => MediaRecorder.isTypeSupported(type));
      const rec = mimeType ? new MediaRecorder(stream, { mimeType }) : new MediaRecorder(stream); recorder.current = rec; const chunks: Blob[] = [];
      rec.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
      rec.onstop = () => { stream.getTracks().forEach(t => t.stop()); void (async () => { setBusy("voice"); try { const form = new FormData(); form.append("audio", new Blob(chunks, { type: rec.mimeType }), rec.mimeType.includes("mp4") ? "question.m4a" : "question.webm"); const response = await fetch("/api/readiness/transcribe", { method: "POST", body: form }); const data = await response.json(); if (!response.ok || !data.transcript) throw new Error(data.error || "We couldn’t transcribe that. Please try again."); setDraft(v => [v, data.transcript].filter(Boolean).join(" ")); } catch (e) { setError(e instanceof Error ? e.message : "Voice transcription failed."); } finally { setBusy(""); } })(); };
      rec.start(250); setRecording(true); setError("");
    } catch (e) { setError(e instanceof Error ? e.message : "Microphone access wasn’t available."); }
  }
  async function sendEmail(e?: React.FormEvent) {
    e?.preventDefault(); if (!saved.report || busy) return; setBusy("email"); setError(""); event("email_report_requested");
    try { const data = await post("/api/readiness/report-email", { sessionId: saved.sessionId, email: saved.email || email, name: saved.name || name, role: saved.role || role, shareRequestWithMsi: true, organisation: saved.candidate?.name, result: emailResult(saved.report, saved.messages.filter(m => m.role === "user").map(m => m.content)), impactMode: saved.candidate?.entityType !== "registered_charity" }); if (!data.ok || !data.attachment?.endsWith(".pdf")) throw new Error("The full PDF was not confirmed as attached. Please retry."); setSaved(s => ({ ...s, emailSent: true })); event("pdf_email_sent"); }
    catch (e) { setError(e instanceof Error ? e.message : "Email failed. No success was confirmed."); } finally { setBusy(""); }
  }
  async function saveFeedback(phase: "quick" | "final", rating: number, comment: string) {
    if (!rating && !comment.trim()) return;
    try { await post("/api/published-review", { operation: "feedback", sessionId: saved.sessionId, organisation: saved.candidate?.name, rating, comment, phase }); event(phase === "quick" ? "snapshot_feedback_rating" : "final_feedback_rating", { rating }); }
    catch { setError("Feedback could not be sent just now. You can still continue."); }
  }
  async function finishReport() {
    if (!saved.report) return; go("generating"); setProgress(["Bringing together your evidence", "Adding what you told us", "Checking the relevant SORP requirements", "Prioritising what matters next"]);
    await sendEmail(); setSaved(s => ({ ...s, step: "report" })); event("full_report_viewed");
  }
  async function contribute() {
    const amountMinor = supportPence(support, custom); if (!amountMinor || busy) return; setBusy("support"); setError(""); event("support_payment_started", { amountMinor, currency: "GBP", paymentType: "voluntary_support" });
    try { const data = await post("/api/sorp-payments/checkout", { paymentType: "voluntary_support", band: null, amountMinor, sessionId: saved.sessionId, organisation: saved.candidate?.name, idempotencyKey: `${saved.sessionId}:support:${amountMinor}:${crypto.randomUUID()}` }); const url = new URL(data.url); if (url.hostname !== "checkout.stripe.com") throw new Error("Secure checkout could not be opened."); window.location.assign(url.href); }
    catch (e) { setError(e instanceof Error ? e.message : "Please try again."); setBusy(""); }
  }
  const report = saved.report, summary = report ? highlights(report.tar) : null, candidates = saved.research?.candidates || [], step = saved.step || "organisation";
  const progressIndex = Math.max(0, steps.findIndex(item => item.step === (step === "quick-feedback" || (step === "generating" && !report) || step === "non-sorp" ? "snapshot" : step === "generating" || step === "final-feedback" || step === "next" ? "report" : step)));
  const feedback = (phase: "quick" | "final") => { const isQuick = phase === "quick", rating = isQuick ? saved.rating : saved.finalRating || 0, comment = isQuick ? saved.comment : saved.finalComment || ""; return <div className="sp-feedback-controls"><div className="sp-stars" aria-label="How useful was this?">{[1, 2, 3, 4, 5].map(value => <button key={value} aria-label={`${value} out of 5`} aria-pressed={rating === value} onClick={() => { setSaved(s => ({ ...s, [isQuick ? "rating" : "finalRating"]: value })); void saveFeedback(phase, value, comment); }}>{value <= rating ? "★" : "☆"}</button>)}</div><p className="sp-small">1 = Not useful yet · 5 = Extremely useful</p><label htmlFor={`sp-${phase}-comment`}>Anything we could improve? <small>(optional)</small></label><textarea id={`sp-${phase}-comment`} value={comment} onChange={e => setSaved(s => ({ ...s, [isQuick ? "comment" : "finalComment"]: e.target.value }))} onBlur={() => { if (comment.trim()) void saveFeedback(phase, rating, comment); }} maxLength={2000}/></div>; };
  return <div className="sorp-public">
    <header className="sp-header"><a href="/">MY SOCIAL IMPACT</a><span>Are You SORP Ready?</span><small>{report ? saved.candidate?.name : "Published evidence. Clear next steps."}</small></header>
    <nav className="sp-progress" aria-label="Your review progress">{steps.map((item, index) => <span key={item.step} className={index === progressIndex ? "is-current" : index < progressIndex ? "is-complete" : ""} aria-current={index === progressIndex ? "step" : undefined}>{index < progressIndex ? "✓" : index + 1}. {item.label}</span>)}</nav>
    <main className="sp-main">
      {step === "generating" ? <section className="sp-generation" aria-live="polite"><p className="sp-kicker">{report ? "YOUR FULL FREE REPORT" : "YOUR PUBLIC-EVIDENCE REVIEW"}</p><h1>{report ? "Building your full report…" : "The homework is happening."}</h1><ul>{(report ? ["Bringing together your evidence", "Adding what you told us", "Checking the relevant SORP requirements", "Prioritising what matters next", "Preparing and emailing your PDF"] : ["Bringing together your public evidence", "Statutory reporting assessed", "Wider evidence assessed separately"]).map(item => <li key={item} className={progress.includes(item) ? "is-done" : ""}>{progress.includes(item) ? "✓" : "—"} {item}</li>)}</ul>{report && <div className="sp-brand-moment"><h2>SORP is the requirement.<br/><em>Better impact is the opportunity.</em></h2><p>My Social Impact is not just about compliance. Better impact information should help organisations learn, make better decisions, improve delivery and communicate impact with confidence.</p><small>BUILT WITH THE IDEAS SHED</small></div>}</section>
      : step === "organisation" ? <section className="sp-entry"><div><p className="sp-kicker">YOUR FREE PUBLISHED-EVIDENCE REVIEW</p><h1>Are you<br/>SORP ready?</h1><p className="sp-lead">Let’s see what your latest reporting tells us.</p><p>We’ll find your charity, read the public evidence and show you what looks strong, what needs attention and why.</p><form onSubmit={e => { e.preventDefault(); void find(); }} className="sp-search"><label htmlFor="charity-query">{saved.research ? "Refine the search with a name, number or website" : "Your charity’s name, number or website"}</label><input id="charity-query" value={query} onChange={e => setQuery(e.target.value)} placeholder="Start with your charity…" required/><button disabled={!!busy || !query.trim()}>{busy === "search" ? "SEARCHING…" : "FIND MY CHARITY →"}</button></form><p className="sp-small">Full review and report included. No card required.</p>
        {busy === "search" && <p role="status" className="sp-notice">Searching for your charity. Hang on a moment…</p>}
        {saved.research && !candidates.length && <p className="sp-notice">We haven’t found a reliable match yet. Add the charity number, its website, or where it works to narrow the search.</p>}
        {candidates.map(c => <article className="sp-candidate" key={c.officialUrl + c.name}><p className="sp-kicker">IS THIS YOUR ORGANISATION?</p><h2>{c.name}</h2><p>{c.registrationNumber && `Registration ${c.registrationNumber} · `}{c.locality}</p><p>{c.summary}</p><p className="sp-small"><SourceLink url={c.officialUrl}>Official record</SourceLink>{" · "}<SourceLink url={c.website}>Website</SourceLink></p><button disabled={!!busy} onClick={() => void confirm(c)}>{busy === "profile" ? "CHECKING PUBLIC RECORD…" : "YES — THAT’S MY ORGANISATION →"}</button></article>)}
        {saved.candidate && !candidates.length && <button disabled={!!busy} onClick={() => void confirm(saved.candidate!)}>RETRY {saved.candidate.name} →</button>}
      </div><aside className="sp-entry-note"><span className="sp-kicker">THE HOMEWORK IS OURS.</span><h2>The evidence.<br/>The requirements.<br/>Your next move.</h2><div><b>01 / Real public evidence</b><p>Your Trustees’ Annual Report and accounts. Impact reports and website evidence, kept separate.</p></div><div><b>02 / SORP as the source of truth</b><p>See the requirement, the evidence and the reasoning behind each important finding.</p></div><div><b>03 / A useful answer, not a questionnaire</b><p>A retrospective starting point—not a claim to know everything happening in your charity today.</p></div></aside></section>
      : step === "evidence" && saved.candidate ? <section className="sp-stage"><p className="sp-kicker">EVIDENCE · WHAT WE FOUND</p><h1>We’ve done the public homework.</h1><p className="sp-lead">{saved.candidate.name}</p><div className="sp-evidence-grid"><div><b>Organisation & legal status</b><p>{saved.candidate.entityType === "registered_charity" ? "Registered charity" : saved.candidate.entityType.replaceAll("_", " ")} · {saved.candidate.registrationNumber || "Registration not established"}</p><SourceLink url={saved.candidate.officialUrl}>Official record</SourceLink></div><div><b>Latest TAR & accounts</b><p>{saved.candidate.reportTitle || "Not established"} · {saved.candidate.reportPeriod || "Period not established"}</p><SourceLink url={saved.candidate.reportUrl}>View source</SourceLink></div><div><b>Accounting basis</b><p>{saved.candidate.accountingBasis || "Not established"} · {saved.candidate.accountingBasisConfidence || "Confidence not established"}</p></div><div><b>Impact Report</b><p>{saved.candidate.publicReadiness?.impactReport?.found ? saved.candidate.publicReadiness.impactReport.title : "None found publicly"}</p><SourceLink url={saved.candidate.publicReadiness?.impactReport?.url || ""}>View source</SourceLink></div><div><b>Website / public evidence</b><p><SourceLink url={saved.candidate.website}>{saved.candidate.website || "Not established"}</SourceLink></p></div></div><form className="sp-identity" onSubmit={e => void buildReview(e)}><h2>Where should we send your personalised report?</h2><p>We’ll use your email to save your review and send you your personalised PDF report.</p><label>Email <input type="email" required value={email} onChange={e => setEmail(e.target.value)} autoComplete="email"/></label><label>Name <small>(optional)</small><input value={name} onChange={e => setName(e.target.value)} autoComplete="name"/></label><label>Role <small>(optional)</small><select value={role} onChange={e => setRole(e.target.value)}><option value="">Select if useful</option>{["CEO / senior leader", "Trustee", "Finance", "Impact / evaluation", "Adviser / accountant", "Other"].map(option => <option key={option}>{option}</option>)}</select></label><button disabled={!!busy || !email.trim()}>BUILD MY FREE REVIEW →</button></form></section>
      : step === "snapshot" && report ? <section className="sp-stage"><p className="sp-kicker">YOUR PUBLISHED-EVIDENCE SNAPSHOT</p><h1>Based on your latest published reporting,<br/>here’s where you appear to stand.</h1><div className="sp-scores"><LensScore lens={report.tar} title="TRUSTEES’ ANNUAL REPORT READINESS"/><LensScore lens={report.wider} title="WIDER EVIDENCE VIEW"/></div><p className="sp-distinction">Wider evidence may show stronger practice. It does not increase the TAR-only score or replace reporting required in the Trustees’ Annual Report.</p><div className="sp-summary"><div><h2>What looks strong</h2>{summary!.strong.map(f => <FindingRow key={f.fieldId} finding={f}/>)}</div><div><h2>Most important gaps</h2>{summary!.gaps.map(f => <FindingRow key={f.fieldId} finding={f}/>)}</div></div><section className="sp-priorities"><p className="sp-kicker">TOP PRIORITIES</p><ol>{summary!.priorities.map(f => <li key={f.fieldId}>{f.action}</li>)}</ol></section><details className="sp-method"><summary>What MUST, SHOULD, MAY and MSI judgement mean?</summary><p>MUST is required by SORP; SHOULD is recommended; MAY is optional. MSI judgement is our interpretation of evidence and proportionality, not an official SORP category.</p><SourceLink url={sorpSource}>SORP 2026 source of truth</SourceLink></details><button className="sp-stage-action" onClick={() => go("quick-feedback")}>CONTINUE →</button></section>
      : step === "quick-feedback" ? <section className="sp-stage sp-short"><p className="sp-kicker">A QUICK, OPTIONAL MOMENT</p><h1>Are you finding this tool useful?</h1><p>A quick rating helps us improve it.</p>{feedback("quick")}<button className="sp-stage-action" onClick={() => go("changed")}>CONTINUE →</button></section>
      : step === "changed" && report ? <section className="sp-stage sp-short"><p className="sp-kicker">WHAT’S CHANGED?</p><h1>This snapshot is based on published evidence.<br/>A lot may have changed since then.<br/>Want to tell us what’s different now?</h1><p>You can explain current practice, correct an outdated finding, challenge a conclusion or ask about SORP. This is a conversation, not another questionnaire.</p><button className="sp-secondary" onClick={() => setChatOpen(true)}>TELL MSI WHAT’S CHANGED →</button><button className="sp-stage-action" disabled={!!busy} onClick={() => { event("guided_conversation_completed", { currentStage: 4 }); void finishReport(); }}>BUILD MY FULL REPORT →</button></section>
      : step === "non-sorp" && report ? <section className="sp-stage"><p className="sp-kicker">ORGANISATION CHECK</p><h1>SORP 2026 does not apply to your organisation as a compliance requirement.</h1><p className="sp-lead">SORP may not be your requirement. Better impact is still the opportunity.</p><p>{report.candidate.name} · {report.candidate.entityType.replaceAll("_", " ")}</p><p><SourceLink url={report.candidate.officialUrl}>Official entity evidence</SourceLink></p><h2>Impact reporting snapshot</h2><p>This uses published evidence and relevant SORP impact-reporting principles as a benchmark, not a compliance score.</p><LensScore lens={report.wider} title="WIDER EVIDENCE VIEW"/><button className="sp-stage-action" onClick={() => { setPanel("deep"); event("deep_dive_clicked"); }}>WANT TO UNDERSTAND HOW STRONG YOUR IMPACT PRACTICE IS OVERALL? →</button></section>
      : step === "report" && report ? <article className="sp-report">
        <div className="sp-report-heading"><div><p className="sp-kicker">YOUR FREE REPORT · PUBLISHED EVIDENCE</p><h1>Here’s where<br/>you stand.</h1><p className="sp-lead">{report.candidate.name}</p></div><div className="sp-report-meta"><p>{report.tar.period || report.candidate.reportPeriod || "Latest published reporting"}</p><p className="sp-small">Prepared {new Date(report.createdAt).toLocaleDateString("en-GB")}<br/>Narrative & impact-reporting readiness</p><button className="sp-secondary" onClick={() => window.print()}>PRINT / SAVE PDF</button></div></div>
        <p className="sp-scope">A look back at your published evidence—not a verdict on everything you do today, and not a certificate of full SORP compliance.</p>
        {(report.candidate.entityType !== "registered_charity" || report.tar.accountingBasis === "receipts") && <p className="sp-notice">SORP may not apply to this entity or accounting basis. Treat the following as wider narrative-reporting guidance, not statutory requirements for this organisation. Ask MSI about your circumstances.</p>}
        <div className="sp-scores"><LensScore lens={report.tar} title="TRUSTEES’ ANNUAL REPORT READINESS"/><LensScore lens={report.wider} title="WIDER EVIDENCE VIEW"/></div><p className="sp-distinction">Wider evidence can show stronger organisational practice. It does not automatically satisfy what should be reported in the Trustees’ Annual Report.</p>
        {(!report.tar.readable || !report.wider.readable) && <div className="sp-notice"><p>Some source material could not be assessed. The report below makes that gap explicit; no score has been invented for unread evidence.</p><button className="sp-secondary" disabled={!!busy} onClick={() => { go("evidence"); }}>REVIEW PUBLIC EVIDENCE</button></div>}
        <section className="sp-summary"><div><p className="sp-kicker">FROM YOUR STATUTORY REPORT</p><h2>What looks strong</h2>{summary!.strong.length ? summary!.strong.map(f => <FindingRow key={f.fieldId} finding={f}/>) : <p>No clear strengths could be established from the statutory material inspected.</p>}</div><div><p className="sp-kicker">WHERE TO FOCUS</p><h2>Most important gaps</h2>{summary!.gaps.length ? summary!.gaps.map(f => <FindingRow key={f.fieldId} finding={f}/>) : <p>{report.tar.readable ? "No major gap was identified in the scored narrative fields. This is not a complete compliance audit." : "Access to the statutory report is the first evidence gap to resolve."}</p>}</div></section>
        <section className="sp-priorities"><p className="sp-kicker">YOUR NEXT MOVE</p><h2>Start here.</h2><ol>{summary!.priorities.map(f => <li key={f.fieldId}><span className="sp-tag">{classificationLabel(f.classification)}</span><p>{f.action}</p></li>)}{!summary!.priorities.length && <li><p>{report.tar.readable ? "Review these conclusions with your trustees and use the evidence trail to prepare your next report." : "Locate a readable copy of the latest statutory report before drawing a readiness conclusion."}</p></li>}</ol></section>
        <details className="sp-evidence"><summary>EXPLORE THE FULL EVIDENCE TRAIL →</summary><p className="sp-kicker">VERIFIED PUBLISHED EVIDENCE · MSI JUDGEMENT · CONFIDENCE</p><h2>No black box.</h2><p>Open any finding to see the SORP source, the evidence, MSI’s reasoning and confidence.</p><div className="sp-legend"><p><b>MUST</b> Required by SORP.</p><p><b>SHOULD</b> Recommended by SORP.</p><p><b>MAY</b> Optional/permitted by SORP.</p><p><b>MSI JUDGEMENT</b> Context, evidence and proportionality—not an official fourth SORP category.</p></div>
          {[report.tar, report.wider].map(lens => <section key={lens.lens} className="sp-lens-detail"><h3>{lens.lens === "tar" ? "Trustees’ Annual Report · statutory evidence only" : "Wider evidence · website & impact reporting"}</h3><p className="sp-small"><SourceLink url={lens.sourceUrl}>{lens.title}</SourceLink> {lens.period}</p>{lens.findings.map(f => <FindingRow key={f.fieldId} finding={f}/>)}</section>)}
          <details className="sp-method"><summary>Methodology, scope & known limits</summary><p>{methodology}</p><p>This focuses on SORP’s narrative and impact-reporting requirements. Financial reporting modules and conditional checks—including fundraising, group reporting and sustainability—may need separate review. No MAY gap is implied merely because an optional disclosure is absent.</p><p>Latest published income: {report.candidate.latestIncome === null ? "not established" : new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(report.candidate.latestIncome)}. Accounting basis: {report.tar.accountingBasis === "unknown" ? "not established by the direct document review" : `${report.tar.accountingBasis} accounts, observed in the statutory document`}. Reporting period: {report.tar.period || "not established"}.</p><SourceLink url={sorpSource}>Read the authoritative SORP 2026</SourceLink></details>
        </details>
        <section className="sp-judgement"><p className="sp-kicker">WHERE HUMAN JUDGEMENT HELPS</p><h2>The evidence is a starting point.</h2>{report.tar.findings.filter(f => ["JUDGEMENT", "MSI_READINESS"].includes(f.classification)).slice(0, 3).map(f => <p key={f.fieldId}>{f.reason}</p>)}<p>What has changed since publication? Is your evidence proportionate? Which claims can you stand behind? These need current context, not another automatic score.</p></section>
        <p className="sp-notice">Verified published evidence is kept separate from information you supplied in conversation. Your current context informs discussion and priorities; it does not silently change the retrospective TAR score.</p>{saved.messages.some(m => m.role === "user") && <details className="sp-method"><summary>Conversation notes · not independently verified</summary>{saved.messages.filter(m => m.role === "user").map((m, i) => <p key={i}>{m.content}</p>)}</details>}
        <button className="sp-stage-action" onClick={() => go("final-feedback")}>CONTINUE →</button>
      </article>
      : step === "final-feedback" ? <section className="sp-stage sp-short"><p className="sp-kicker">OPTIONAL FEEDBACK</p><h1>How useful was the full experience?</h1><p>Your feedback helps us make this more useful for the next charity that uses it.</p>{feedback("final")}<button className="sp-stage-action" onClick={() => { go("next"); event("support_ask_viewed"); event("deep_dive_offer_viewed"); }}>CONTINUE →</button></section>
      : step === "next" && report ? <section className="sp-stage"><p className="sp-kicker">YOUR NEXT STEPS</p><h1>What would you like to do next?</h1><div className="sp-next-grid"><div><p className="sp-kicker">HELP US KEEP THIS FREE</p><p>If this helped, £5 — or whatever you can afford — helps us keep building and running free tools, especially for smaller charities.</p>{saved.supportDeclined ? <p role="status">No problem. Your free report is yours.</p> : <><div className="sp-amounts">{([5, 10, 20, "other"] as const).map(amount => <button key={amount} className={support === amount ? "" : "sp-secondary"} onClick={() => setSupport(amount)}>{amount === "other" ? "OTHER" : `£${amount}`}</button>)}</div>{support === "other" && <label>Amount in pounds<input inputMode="decimal" value={custom} onChange={e => setCustom(e.target.value)}/></label>}<button disabled={!!busy || !supportPence(support, custom)} onClick={() => void contribute()}>SUPPORT THE FREE TOOL →</button><button className="sp-quiet" onClick={() => setSaved(s => ({ ...s, supportDeclined: true }))}>NOT NOW</button></>}</div><div><p className="sp-kicker">CURRENT READINESS DEEP-DIVE</p><h2>Want to know where you actually are now?</h2><p><b>Free:</b> What does your latest published evidence tell us?</p><p><b>Paid Deep-Dive:</b> Where are you actually now, how ready are you for your next reporting period, and what do you need to do next?</p><button onClick={() => { setPanel("deep"); event("deep_dive_clicked"); }}>EXPLORE THE SORP CURRENT READINESS DEEP-DIVE →</button><p className="sp-small">Not sure? <a href="mailto:marcus@mysocialimpact.org?subject=SORP%2010-minute%20conversation" onClick={() => event("ten_minute_call_clicked")}>Talk to us for 10 minutes ↗</a></p></div></div></section>
      : null}
      {error && <p role="alert" className="sp-error">{error}</p>}
      {panel && report && <div ref={panelRef} className="sp-panel"><button className="sp-secondary sp-close" onClick={() => setPanel(null)}>CLOSE ×</button>{panel === "email" ? <><h2>Keep your full report.</h2><p>We’ll attach the complete PDF. You’ll stay right here.</p>{saved.emailSent ? <p role="status" className="sp-notice">SENT ✓ Your full PDF has been sent. Your review and next actions are still here.</p> : <form onSubmit={sendEmail} className="sp-email-form"><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></label><label>Name <small>(optional)</small><input value={name} onChange={e => setName(e.target.value)}/></label><label>Role <small>(optional)</small><input value={role} onChange={e => setRole(e.target.value)}/></label><p className="sp-small">We’ll email your full PDF and share a copy of your request with My Social Impact, including any name and role you choose to add. No account or marketing subscription.</p><button disabled={!!busy}>{busy === "email" ? "SENDING FULL PDF…" : "EMAIL MY PDF →"}</button></form>}</> : panel === "support" ? <><h2>Help keep this free.</h2><p>A voluntary contribution helps us keep improving useful tools for charities.</p><div className="sp-amounts">{([5, 10, 20, "other"] as const).map(amount => <button key={amount} className={support === amount ? "" : "sp-secondary"} onClick={() => setSupport(amount)}>{amount === "other" ? "Another amount" : `£${amount}`}</button>)}</div>{support === "other" && <label>Amount in pounds (£1–£1,000)<input inputMode="decimal" value={custom} onChange={e => setCustom(e.target.value)}/></label>}<button disabled={!!busy || !supportPence(support, custom)} onClick={() => void contribute()}>{busy === "support" ? "OPENING SECURE CHECKOUT…" : "CONTINUE TO SECURE CHECKOUT →"}</button><p className="sp-small">Opens the existing secure Stripe payment page. Your report is saved on this device.</p></> : <SorpPublicDeepDive report={report} state={saved.state} sessionId={saved.sessionId} onContextChange={setPrototypeContext}/>}</div>}
      <footer className="sp-version">{PUBLIC_BUILD}{saved.intelligence && <details><summary>MSI Intelligence · {saved.intelligence.effectiveVersion}</summary>{saved.intelligence.layers.map(layer => <p key={layer.name}>{layer.name} · {layer.label}</p>)}</details>}</footer>
    </main>
    {chatOpen && <aside className="sp-chat" aria-label="Ask My Social Impact"><div className="sp-chat-head"><b>Ask My Social Impact</b><button className="sp-secondary" onClick={() => setChatOpen(false)} aria-label="Close conversation">×</button></div><div className="sp-chat-history">{!saved.messages.length && <p>Ask about the evidence, a SORP requirement, or what this means for your charity.</p>}{saved.messages.map((m, i) => <div key={i} className={`sp-message sp-${m.role}`}><small>{m.role === "user" ? "YOU" : "MY SOCIAL IMPACT INTELLIGENCE"}</small><p>{m.content}</p>{m.citations?.map(c => <details key={c.reference}><summary>SORP {c.reference}</summary><p>{c.extract}</p></details>)}</div>)}{busy === "chat" && <p role="status">Thinking about your question…</p>}<div ref={chatEnd}/></div>{error && <p role="alert" className="sp-error">{error}</p>}<form onSubmit={e => { e.preventDefault(); void sendMessage(); }}><label htmlFor="sp-chat-input">Your question or context</label><textarea id="sp-chat-input" value={draft} onChange={e => setDraft(e.target.value)} maxLength={4000}/><div><button type="button" className="sp-secondary" disabled={!!busy} onClick={() => void microphone()}>{recording ? "STOP RECORDING" : "USE MICROPHONE"}</button><button disabled={!!busy || !draft.trim() || recording}>{busy === "voice" ? "TRANSCRIBING…" : "SEND →"}</button></div></form></aside>}
    <div className="sp-actionbar">{step === "report" || step === "next" ? <button className="sp-secondary" disabled={saved.emailSent} onClick={() => void sendEmail()}>{saved.emailSent ? "PDF SENT ✓" : "EMAIL MY PDF →"}</button> : <span className="sp-small">Your charity. Its real evidence. A useful first answer.</span>}<button className="sp-secondary" onClick={() => setChatOpen(v => !v)}>{chatOpen ? "CLOSE CHAT" : "ASK MSI"}</button></div>
  </div>;
}
