import type { Tier } from "./sorp-questionnaire";

export type ScreeningAnswer = "yes" | "no" | "not_sure";
export type CheckAnswer = "yes" | "mostly" | "partly" | "not_yet" | "not_sure" | "not_applicable";
export type CurrentAdditionalCheck = {
  id: string;
  title: string;
  screening?: string;
  question: string;
  why: string;
  when: string;
  expects: string;
  classification: "MUST" | "SHOULD";
  tiers: readonly Tier[];
  jurisdictions?: readonly string[];
  sources: readonly { reference: string; page: number; text: string }[];
};

const all: Tier[] = ["tier1", "tier2", "tier3"];
const larger: Tier[] = ["tier2", "tier3"];

// Separate from the frozen Advanced questionnaire. Paragraphs and applicability
// were checked against the uploaded Charities SORP 2026, module 1 (PDF pp. 27–38).
export const currentAdditionalChecks: CurrentAdditionalCheck[] = [
  { id: "volunteers", title: "Volunteers", screening: "Do volunteers contribute to the charity’s activities?", question: "Can your Trustees’ Annual Report explain the scale and nature of volunteer input and the activities volunteers support?", why: "Volunteer contribution may not appear in the financial statements, so the report needs to explain it.", when: "Where volunteers contribute to the charity’s activities, at any SORP tier.", expects: "MUST explain the scale and nature of volunteer input. The SORP also says charities reporting general volunteers SHOULD give numbers and describe supported activities.", classification: "MUST", tiers: all, sources: [{ reference: "1.21", page: 30, text: "The report must explain the scale and nature of activities and input from volunteers." }, { reference: "1.26", page: 31, text: "Charities reporting general volunteers should provide volunteer numbers and the activities they support." }] },
  { id: "grant_making", title: "Material grant-making", screening: "Is grant-making a material part of the charity’s activities?", question: "Can your report explain the policy for selecting grant recipients?", why: "Readers need to understand how material grants advance the charity’s purposes.", when: "Tier 2 or 3, where grant-making forms a material part of charitable activities.", expects: "MUST explain the grant-making policy for selecting individuals or institutions.", classification: "MUST", tiers: larger, sources: [{ reference: "1.25", page: 30, text: "Where grant-making is material, the report must explain the selection policy for grant recipients." }] },
  { id: "social_investment", title: "Material social investment", screening: "Is social investment a material part of the charity’s activities or investments?", question: "Can your report explain the social investment policies and how those investments contribute to the charity’s aims?", why: "Material social investments need an explanation of purpose as well as financial treatment.", when: "Tier 2 or 3, where social investment forms a material part of charitable and investment activities.", expects: "MUST explain social investment policies and their contribution to aims and objectives.", classification: "MUST", tiers: larger, sources: [{ reference: "1.25", page: 30, text: "Where social investment is material, the report must explain its policies and contribution to aims and objectives." }] },
  { id: "fundraising", title: "Material fundraising", screening: "Does the charity undertake material fundraising activity or incur material fundraising costs?", question: "Can your report review fundraising performance against objectives and the effect of material costs on returns?", why: "Tier 3 reporting links fundraising effort and expenditure to results.", when: "Tier 3, when fundraising activity or expenditure is material.", expects: "MUST review material fundraising performance and explain the effect of material expenditure on net returns for this and future periods.", classification: "MUST", tiers: ["tier3"], sources: [{ reference: "1.33", page: 32, text: "Tier 3 reports must review material fundraising performance and the effect of material fundraising expenditure on net returns." }] },
  { id: "audited_fundraising", title: "Audited fundraising practices", screening: "Is this England-and-Wales charity subject to audit?", question: "Does the Trustees’ Annual Report disclose the charity’s fundraising practices?", why: "SORP points to an additional statutory TAR disclosure for charities subject to audit in England and Wales.", when: "England and Wales charities that are subject to audit, at any SORP tier.", expects: "MUST disclose fundraising practices in the report under the cited legislation.", classification: "MUST", tiers: all, jurisdictions: ["ew"], sources: [{ reference: "1.7", page: 27, text: "England and Wales charities subject to audit must disclose information on fundraising practices in their report." }] },
  { id: "investments", title: "Material financial investments", screening: "Does the charity hold material financial investments?", question: "Can your report review investment performance against objectives and explain the policy for selecting, retaining and realising investments?", why: "Material investments call for a performance review and an account of trustees’ investment policy.", when: "Tier 2 or 3, where material financial investments are held.", expects: "MUST review performance against investment objectives and explain the selection, retention and realisation policies, including relevant social, environmental or ethical considerations.", classification: "MUST", tiers: larger, sources: [{ reference: "1.29", page: 31, text: "The report must review material investment performance against the objectives set." }, { reference: "1.44", page: 33, text: "The report must explain policies for selecting, retaining and realising material investments and relevant social, environmental or ethical considerations." }] },
  { id: "group", title: "Subsidiaries / charity group", screening: "Does the charity have a subsidiary or form part of a group?", question: "Can your report explain relevant subsidiary activities, performance and group relationships?", why: "Group activities and relationships affect how users understand performance and governance.", when: "Tier 2 or 3, where subsidiaries or relevant group relationships exist.", expects: "MUST cover subsidiary performance where applicable, organisational structure and relevant relationships.", classification: "MUST", tiers: larger, sources: [{ reference: "1.28", page: 31, text: "The report must cover how the charity and any subsidiaries carried out their activities." }, { reference: "1.52", page: 35, text: "The report must explain the charity’s and relevant subsidiaries’ organisational structures." }, { reference: "1.54", page: 35, text: "The report must explain relevant relationships with subsidiaries and related parties." }] },
  { id: "material_deficit", title: "Material deficit", screening: "Is any fund or subsidiary undertaking materially in deficit?", question: "Can your report identify the material deficit, explain its cause and the steps being taken to eliminate it?", why: "A material deficit needs a specific explanation rather than being left to the figures alone.", when: "Any tier, if a fund or subsidiary undertaking is materially in deficit.", expects: "MUST identify the deficit, explain the circumstances and the steps to eliminate it.", classification: "MUST", tiers: all, sources: [{ reference: "1.35", page: 32, text: "The report must identify a materially deficit fund or subsidiary, explain the circumstances and the steps to eliminate the deficit." }] },
  { id: "designated_funds", title: "Material designated funds", screening: "Are material reserves designated or otherwise committed?", question: "Can your report explain material designated or committed amounts and when they are likely to be spent?", why: "The reserves review should show what is already committed and when it may be used.", when: "Any tier, where material funds are designated or otherwise committed at period end.", expects: "MUST explain material designated or committed amounts and indicate likely spending timing.", classification: "MUST", tiers: all, sources: [{ reference: "1.40", page: 33, text: "The reserves review must explain material designated or committed amounts and their likely expenditure timing." }] },
  { id: "going_concern", title: "Going concern uncertainty", screening: "Are there no reserves, negative net assets, or material uncertainties about continuing as a going concern?", question: "Can your report explain why the charity remains a going concern and any material uncertainties?", why: "These circumstances require an explicit explanation in the Trustees’ Annual Report.", when: "Any tier, if reserves are absent, net assets are negative, or material going-concern uncertainty exists.", expects: "MUST explain continued operation where there are no reserves or negative net assets, and MUST explain material going-concern uncertainties.", classification: "MUST", tiers: all, sources: [{ reference: "1.41", page: 33, text: "Where a charity has no reserves or negative net assets, it must explain why it remains a going concern." }, { reference: "1.42", page: 33, text: "Material uncertainties about going concern at approval must be explained." }] },
  { id: "pension", title: "Defined-benefit pension", screening: "Is there a material defined-benefit pension liability or asset?", question: "Does the financial review explain the effect of the material pension liability or asset on the charity’s position?", why: "A material pension position can materially change how users understand available resources.", when: "Tier 2 or 3, if there is a material defined-benefit pension liability or asset.", expects: "SHOULD give a narrative explanation of the effect on financial position.", classification: "SHOULD", tiers: larger, sources: [{ reference: "1.45", page: 34, text: "The financial review should explain the impact of a material defined-benefit pension liability or asset." }] },
  { id: "legacy", title: "Material legacy income", screening: "Was material legacy income recognised before it was received?", question: "Does the financial review explain how the timing of material legacy income affects available resources?", why: "Recognition before receipt may make resources appear more readily available than they are.", when: "Tier 2 or 3, if material legacy income was recognised before receipt.", expects: "SHOULD explain the effect of the timing difference on available resources.", classification: "SHOULD", tiers: larger, sources: [{ reference: "1.45", page: 34, text: "The financial review should explain material legacy income recognised before receipt and its effect on available resources." }] },
  { id: "principal_risks", title: "Principal risks", question: "Can your report describe principal risks and uncertainties, including relevant environmental or cyber risks, and plans to manage them?", why: "Risk disclosure helps users understand the charity’s financial position and future resilience.", when: "All Tier 2 and Tier 3 charities.", expects: "MUST describe principal risks and uncertainties, with a summary of management plans and strategies.", classification: "MUST", tiers: larger, sources: [{ reference: "1.43", page: 33, text: "The report must describe principal risks and uncertainties, including relevant environmental and cyber risks, and plans for managing them." }] },
  { id: "governance", title: "Governance and management", question: "Can your report explain trustee induction, key decisions and delegation, and how key management pay is set?", why: "Tier 2 and Tier 3 reports must make their governance and management arrangements understandable.", when: "All Tier 2 and Tier 3 charities.", expects: "MUST explain trustee induction and training, decision-making and delegation, and key management remuneration arrangements.", classification: "MUST", tiers: larger, sources: [{ reference: "1.53", page: 35, text: "The report must explain trustee induction and ongoing training policies and procedures." }, { reference: "1.54", page: 35, text: "The report must explain decision-making, delegation and key management remuneration arrangements." }] },
  { id: "sustainability", title: "Sustainability / ESG", question: "Can your report summarise how the charity responds to and manages environmental, governance and social matters?", why: "SORP 2026 makes this a specific Tier 3 reporting requirement.", when: "All Tier 3 charities. Tier 1 and Tier 2 may choose to report on it, but it is not a required extra check here.", expects: "MUST summarise the charity’s response to and management of environmental, governance and social matters.", classification: "MUST", tiers: ["tier3"], sources: [{ reference: "1.61", page: 37, text: "Tier 3 reports must summarise responses to and management of environmental, governance and social matters." }] },
  { id: "future_finance", title: "Future financial factors", question: "Can your report explain factors likely to affect the charity’s financial performance or position going forward?", why: "Tier 3 reporting looks beyond the year-end position.", when: "All Tier 3 charities.", expects: "MUST explain factors likely to affect future financial performance or position.", classification: "MUST", tiers: ["tier3"], sources: [{ reference: "1.46", page: 34, text: "The report must explain factors likely to affect financial performance or position going forward." }] },
];

export function availableAdditionalChecks(tier: Tier | null, jurisdiction?: string) {
  return currentAdditionalChecks.filter(check => (tier ? check.tiers.includes(tier) : check.tiers.length === 3) && (!check.jurisdictions || check.jurisdictions.includes(jurisdiction || "")));
}

export function relevantCurrentChecks(tier: Tier | null, screening: Readonly<Record<string, ScreeningAnswer | undefined>>, jurisdiction?: string) {
  return availableAdditionalChecks(tier, jurisdiction).filter(check => !check.screening || screening[check.id] === "yes");
}

export function additionalStatus(answer: CheckAnswer | undefined, screening: ScreeningAnswer | undefined) {
  if (screening === "no" || answer === "not_applicable") return "Not applicable";
  if (screening === "not_sure") return "Applicability to confirm";
  if (answer === "yes") return "Covered · self-reported";
  if (answer === "mostly" || answer === "partly" || answer === "not_yet") return "Action needed · self-reported";
  if (answer === "not_sure") return "Needs confirmation";
  return "Not yet answered";
}
